// Auto-generated by convert_promo.py — do not edit by hand.
// Run: python convert_promo.py
// No data yet — run the script to populate.
export const GENERATED_AT = null

export const PROMO_ACTIVITY = {
  field: { label: 'ลงพื้นที่', color: '#06B6D4' },
  media: { label: 'ลงสื่อ', color: '#A855F7' },
  looks: { label: 'LOOKS Magazine', color: '#E879F9' },
}

export const PROMO_RETAILERS = []
export const PROMO_META = {}

const promoData = []
export default promoData
