// Auto-generated by convert_to_data.py — do not edit manually
const RETAILER_DATA = {
  "4015000032018": {
    "Tops": {
      "costUnit": 277.5701,
      "costCase": 1387.8505,
      "gp": 0.34
    },
    "Villa": {
      "costUnit": 319.6262,
      "costCase": 1598.1308,
      "gp": 0.24
    },
    "The Mall": {
      "costUnit": 315.42,
      "costCase": 1577.1,
      "gp": 0.25
    },
    "Homepro": {
      "costUnit": 332.243,
      "costCase": 1661.215,
      "gp": 0.21
    },
    "TWD": {
      "costUnit": 332.243,
      "costCase": 1661.215,
      "gp": 0.21
    }
  },
  "4015000319225": {
    "Tops": {
      "costUnit": 277.5701,
      "costCase": 1665.4206,
      "gp": 0.34
    },
    "Villa": {
      "costUnit": 319.6262,
      "costCase": 1917.757,
      "gp": 0.24
    },
    "The Mall": {
      "costUnit": 262.85,
      "costCase": 1577.1,
      "gp": 0.25
    },
    "Homepro": {
      "costUnit": 332.243,
      "costCase": 1993.4579,
      "gp": 0.21
    },
    "TWD": {
      "costUnit": 332.243,
      "costCase": 1993.4579,
      "gp": 0.21
    }
  },
  "4015000032025": {
    "Tops": {
      "costUnit": 314.5794,
      "costCase": 1887.4766,
      "gp": 0.32
    },
    "Villa": {
      "costUnit": 351.5888,
      "costCase": 2109.5327,
      "gp": 0.24
    },
    "The Mall": {
      "costUnit": 297.5,
      "costCase": 1785.0,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 365.6,
      "costCase": 2193.6,
      "gp": 0.2097
    },
    "TWD": {
      "costUnit": 365.4673,
      "costCase": 2192.8037,
      "gp": 0.21
    }
  },
  "5900785708021": {
    "Tops": {
      "costUnit": 174.7664,
      "costCase": 1398.1308,
      "gp": 0.32
    },
    "Villa": {
      "costUnit": 187.6168,
      "costCase": 1500.9346,
      "gp": 0.27
    },
    "The Mall": {
      "costUnit": 187.6168,
      "costCase": 1500.9346,
      "gp": 0.27
    },
    "Homepro": {
      "costUnit": 179.9065,
      "costCase": 1439.2523,
      "gp": 0.3
    },
    "TWD": {
      "costUnit": 205.6075,
      "costCase": 2467.2897,
      "gp": 0.2
    }
  },
  "3450601046834": {
    "Tops": {
      "costUnit": 480.6542,
      "costCase": 3364.5794,
      "gp": 0.26
    },
    "Villa": {
      "costUnit": 474.1589,
      "costCase": 3319.1121,
      "gp": 0.27
    },
    "The Mall": {
      "costUnit": 487.1495,
      "costCase": 3410.0467,
      "gp": 0.25
    },
    "Homepro": {
      "costUnit": 519.6262,
      "costCase": 3637.3832,
      "gp": 0.2
    }
  },
  "3450601031656": {
    "Tops": {
      "costUnit": 192.9907,
      "costCase": 2315.8879,
      "gp": 0.3
    },
    "Villa": {
      "costUnit": 201.2617,
      "costCase": 2415.1402,
      "gp": 0.27
    }
  },
  "024200060572": {
    "Tops": {
      "costUnit": 287.8505,
      "costCase": 1727.1028,
      "gp": 0.2
    },
    "Villa": {
      "costUnit": 284.2523,
      "costCase": 1705.514,
      "gp": 0.21
    },
    "The Mall": {
      "costUnit": 295.0467,
      "costCase": 1770.28,
      "gp": 0.18
    },
    "Lotus": {
      "costUnit": 251.8683,
      "costCase": 1511.2098,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 316.6355,
      "costCase": 1899.8131,
      "gp": 0.12
    },
    "Big C": {
      "costUnit": 287.8505,
      "costCase": 1727.1028,
      "gp": 0.2
    },
    "TWD": {
      "costUnit": 295.0467,
      "costCase": 1770.2804,
      "gp": 0.18
    }
  },
  "4015200033662": {
    "Tops": {
      "costUnit": 206.7757,
      "costCase": 1447.4299,
      "gp": 0.25
    },
    "Villa": {
      "costUnit": 291.6355,
      "costCase": 2333.0841,
      "gp": 0.21
    },
    "The Mall": {
      "costUnit": 291.63,
      "costCase": 2333.08,
      "gp": 0.21
    }
  },
  "8857130119117": {
    "Tops": {
      "costUnit": 276.8692,
      "costCase": 1661.215,
      "gp": 0.25
    },
    "Villa": {
      "costUnit": 291.6355,
      "costCase": 1749.8131,
      "gp": 0.21
    },
    "The Mall": {
      "costUnit": 291.6355,
      "costCase": 1749.8131,
      "gp": 0.21
    },
    "Homepro": {
      "costUnit": 295.3271,
      "costCase": 1771.9626,
      "gp": 0.2
    },
    "TWD": {
      "costUnit": 291.6355,
      "costCase": 1749.8131,
      "gp": 0.21
    },
    "Foodland": {
      "costUnit": 273.1776,
      "costCase": 1639.0654,
      "gp": 0.26
    }
  },
  "8857130119339": {
    "Tops": {
      "costUnit": 276.8692,
      "costCase": 1661.215,
      "gp": 0.25
    },
    "Villa": {
      "costUnit": 291.6355,
      "costCase": 1749.8131,
      "gp": 0.21
    },
    "The Mall": {
      "costUnit": 291.6355,
      "costCase": 1749.8131,
      "gp": 0.21
    },
    "Homepro": {
      "costUnit": 295.3271,
      "costCase": 1771.9626,
      "gp": 0.2
    },
    "TWD": {
      "costUnit": 291.6355,
      "costCase": 1749.8131,
      "gp": 0.21
    },
    "Foodland": {
      "costUnit": 273.1776,
      "costCase": 1639.0654,
      "gp": 0.26
    }
  },
  "8857130119223": {
    "Tops": {
      "costUnit": 276.8692,
      "costCase": 1661.215,
      "gp": 0.25
    },
    "Villa": {
      "costUnit": 291.6355,
      "costCase": 1749.8131,
      "gp": 0.21
    },
    "The Mall": {
      "costUnit": 291.6355,
      "costCase": 1749.8131,
      "gp": 0.21
    },
    "Homepro": {
      "costUnit": 295.3271,
      "costCase": 1771.9626,
      "gp": 0.2
    },
    "TWD": {
      "costUnit": 291.6355,
      "costCase": 1749.8131,
      "gp": 0.21
    },
    "Foodland": {
      "costUnit": 273.1776,
      "costCase": 1639.0654,
      "gp": 0.26
    }
  },
  "8857130119551": {
    "Tops": {
      "costUnit": 356.215,
      "costCase": 2137.2897,
      "gp": 0.23
    },
    "Villa": {
      "costUnit": 365.4673,
      "costCase": 2192.8037,
      "gp": 0.21
    },
    "The Mall": {
      "costUnit": 395.0,
      "costCase": 2370.0,
      "gp": 0.21
    },
    "Homepro": {
      "costUnit": 400.0,
      "costCase": 2400.0,
      "gp": 0.2
    },
    "Foodland": {
      "costUnit": 342.3364,
      "costCase": 2054.0187,
      "gp": 0.26
    }
  },
  "3450601046315": {
    "Tops": {
      "costUnit": 360.8411,
      "costCase": 2165.0467,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 365.4673,
      "costCase": 2192.8037,
      "gp": 0.21
    },
    "The Mall": {
      "costUnit": 379.3458,
      "costCase": 2276.0748,
      "gp": 0.18
    },
    "Homepro": {
      "costUnit": 370.0935,
      "costCase": 2220.5607,
      "gp": 0.2
    },
    "TWD": {
      "costUnit": 379.3458,
      "costCase": 3034.7664,
      "gp": 0.18
    },
    "Foodland": {
      "costUnit": 342.3364,
      "costCase": 2054.0187,
      "gp": 0.26
    }
  },
  "3450601046278": {
    "Tops": {
      "costUnit": 360.8411,
      "costCase": 2165.0467,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 365.4673,
      "costCase": 2192.8037,
      "gp": 0.21
    },
    "The Mall": {
      "costUnit": 379.3458,
      "costCase": 2276.0748,
      "gp": 0.18
    },
    "Homepro": {
      "costUnit": 370.0935,
      "costCase": 2220.5607,
      "gp": 0.2
    },
    "TWD": {
      "costUnit": 379.3458,
      "costCase": 2276.0748,
      "gp": 0.18
    },
    "Foodland": {
      "costUnit": 342.3364,
      "costCase": 2054.0187,
      "gp": 0.26
    }
  },
  "3450601047039": {
    "Tops": {
      "costUnit": 108.4112,
      "costCase": 1300.9346,
      "gp": 0.2
    },
    "Villa": {
      "costUnit": 108.4112,
      "costCase": 1300.9346,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 104.3458,
      "costCase": 1252.1495,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 108.4112,
      "costCase": 1300.9346,
      "gp": 0.2
    },
    "TWD": {
      "costUnit": 108.4112,
      "costCase": 1300.9346,
      "gp": 0.2
    },
    "Foodland": {
      "costUnit": 101.6355,
      "costCase": 1219.6262,
      "gp": 0.25
    }
  },
  "3450601047077": {
    "Tops": {
      "costUnit": 108.4112,
      "costCase": 1300.9346,
      "gp": 0.2
    },
    "Villa": {
      "costUnit": 108.4112,
      "costCase": 1300.9346,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 104.3458,
      "costCase": 1252.1495,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 108.4112,
      "costCase": 1300.9346,
      "gp": 0.2
    },
    "TWD": {
      "costUnit": 108.4112,
      "costCase": 1300.9346,
      "gp": 0.2
    },
    "Foodland": {
      "costUnit": 101.6355,
      "costCase": 1219.6262,
      "gp": 0.25
    }
  },
  "3450601047091": {
    "Tops": {
      "costUnit": 108.4112,
      "costCase": 1300.9346,
      "gp": 0.2
    },
    "Villa": {
      "costUnit": 108.4112,
      "costCase": 1300.9346,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 104.3458,
      "costCase": 1252.1495,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 108.4112,
      "costCase": 1300.9346,
      "gp": 0.2
    },
    "TWD": {
      "costUnit": 108.4112,
      "costCase": 1300.9346,
      "gp": 0.2
    }
  },
  "4015000318150": {
    "Tops": {
      "costUnit": 138.3178,
      "costCase": 1659.8131,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 136.59,
      "costCase": 1639.06,
      "gp": 0.21
    },
    "Homepro": {
      "costUnit": 138.3178,
      "costCase": 1659.8131,
      "gp": 0.2
    },
    "Big C": {
      "costUnit": 115.8879,
      "costCase": 1390.6542,
      "gp": 0.2
    },
    "Foodland": {
      "costUnit": 138.18,
      "costCase": 1659.81,
      "gp": 0.2008
    }
  },
  "4015000318174": {
    "Tops": {
      "costUnit": 138.3178,
      "costCase": 1659.8131,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 136.59,
      "costCase": 1639.06,
      "gp": 0.21
    },
    "Homepro": {
      "costUnit": 138.3178,
      "costCase": 1659.8131,
      "gp": 0.2
    },
    "Big C": {
      "costUnit": 115.8879,
      "costCase": 1390.6542,
      "gp": 0.2
    },
    "Foodland": {
      "costUnit": 138.18,
      "costCase": 1659.81,
      "gp": 0.2008
    }
  },
  "4015000308991": {
    "Tops": {
      "costUnit": 145.7944,
      "costCase": 1749.5327,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 145.8,
      "costCase": 1749.53,
      "gp": 0.2
    },
    "Homepro": {
      "costUnit": 145.7944,
      "costCase": 1749.5327,
      "gp": 0.2
    },
    "Big C": {
      "costUnit": 126.4486,
      "costCase": 1517.3832,
      "gp": 0.18
    }
  },
  "8809004777961": {
    "Tops": {
      "costUnit": 92.1028,
      "costCase": 2210.4673,
      "gp": 0.27
    },
    "Villa": {
      "costUnit": 100.9346,
      "costCase": 2422.4299,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 94.6263,
      "costCase": 2271.03,
      "gp": 0.25
    },
    "Homepro": {
      "costUnit": 100.94,
      "costCase": 2422.56,
      "gp": 0.2
    },
    "Big C": {
      "costUnit": 100.9346,
      "costCase": 2422.4299,
      "gp": 0.2
    },
    "TWD": {
      "costUnit": 94.6262,
      "costCase": 2271.028,
      "gp": 0.25
    },
    "Foodland": {
      "costUnit": 103.4579,
      "costCase": 2482.99,
      "gp": 0.18
    }
  },
  "8809004777978": {
    "Tops": {
      "costUnit": 92.1028,
      "costCase": 2210.4673,
      "gp": 0.27
    },
    "Villa": {
      "costUnit": 100.9346,
      "costCase": 2422.4299,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 94.6263,
      "costCase": 2271.03,
      "gp": 0.25
    },
    "Homepro": {
      "costUnit": 100.94,
      "costCase": 2422.56,
      "gp": 0.2
    },
    "Big C": {
      "costUnit": 100.9346,
      "costCase": 2422.4299,
      "gp": 0.2
    },
    "TWD": {
      "costUnit": 94.6262,
      "costCase": 2271.028,
      "gp": 0.25
    }
  },
  "8809004777985": {
    "Tops": {
      "costUnit": 108.4766,
      "costCase": 2169.5327,
      "gp": 0.27
    },
    "Villa": {
      "costUnit": 118.8785,
      "costCase": 2377.5701,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 111.4,
      "costCase": 2228.0,
      "gp": 0.2503
    },
    "Homepro": {
      "costUnit": 118.88,
      "costCase": 2377.6,
      "gp": 0.2
    },
    "Big C": {
      "costUnit": 118.875,
      "costCase": 2377.5,
      "gp": 0.2
    },
    "TWD": {
      "costUnit": 111.4486,
      "costCase": 2228.972,
      "gp": 0.25
    },
    "Foodland": {
      "costUnit": 118.8785,
      "costCase": 2377.5701,
      "gp": 0.2
    }
  },
  "8809004777992": {
    "Tops": {
      "costUnit": 108.4766,
      "costCase": 2169.5327,
      "gp": 0.27
    },
    "Villa": {
      "costUnit": 118.8785,
      "costCase": 2377.5701,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 111.4,
      "costCase": 2228.0,
      "gp": 0.2503
    },
    "Homepro": {
      "costUnit": 118.88,
      "costCase": 2377.6,
      "gp": 0.2
    },
    "Big C": {
      "costUnit": 118.875,
      "costCase": 2377.5,
      "gp": 0.2
    },
    "TWD": {
      "costUnit": 111.4486,
      "costCase": 2228.972,
      "gp": 0.25
    },
    "Foodland": {
      "costUnit": 121.85,
      "costCase": 2437.0,
      "gp": 0.18
    }
  },
  "8809004776810": {
    "Tops": {
      "costUnit": 126.215,
      "costCase": 1514.5794,
      "gp": 0.27
    },
    "Villa": {
      "costUnit": 138.3178,
      "costCase": 1659.8131,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 133.13,
      "costCase": 1597.57,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 118.88,
      "costCase": 1426.56,
      "gp": 0.2
    },
    "Big C": {
      "costUnit": 138.32,
      "costCase": 1659.81,
      "gp": 0.2
    },
    "TWD": {
      "costUnit": 133.1308,
      "costCase": 1597.5701,
      "gp": 0.23
    },
    "Foodland": {
      "costUnit": 141.77,
      "costCase": 1701.31,
      "gp": 0.18
    }
  },
  "8809004776827": {
    "Tops": {
      "costUnit": 126.215,
      "costCase": 1514.5794,
      "gp": 0.27
    },
    "Villa": {
      "costUnit": 138.3178,
      "costCase": 1659.8131,
      "gp": 0.2
    },
    "Homepro": {
      "costUnit": 118.88,
      "costCase": 1426.56,
      "gp": 0.2
    },
    "Big C": {
      "costUnit": 138.32,
      "costCase": 1659.81,
      "gp": 0.2
    },
    "TWD": {
      "costUnit": 133.1308,
      "costCase": 1597.5701,
      "gp": 0.23
    }
  },
  "4897024513021": {
    "Tops": {
      "costUnit": 87.62,
      "costCase": 1401.92,
      "gp": 0.25
    },
    "Villa": {
      "costUnit": 89.9533,
      "costCase": 1439.2523,
      "gp": 0.23
    },
    "The Mall": {
      "costUnit": 93.4579,
      "costCase": 1495.3271,
      "gp": 0.2
    },
    "Homepro": {
      "costUnit": 87.6168,
      "costCase": 1401.8692,
      "gp": 0.25
    },
    "Big C": {
      "costUnit": 81.7757,
      "costCase": 1308.4112,
      "gp": 0.3
    },
    "Foodland": {
      "costUnit": 87.6168,
      "costCase": 1401.8692,
      "gp": 0.25
    }
  },
  "4897024510198": {
    "Tops": {
      "costUnit": 92.1028,
      "costCase": 1381.5421,
      "gp": 0.27
    },
    "The Mall": {
      "costUnit": 100.9346,
      "costCase": 1514.0187,
      "gp": 0.2
    },
    "Homepro": {
      "costUnit": 94.6262,
      "costCase": 1419.3925,
      "gp": 0.25
    },
    "Big C": {
      "costUnit": 88.3178,
      "costCase": 1324.7664,
      "gp": 0.3
    },
    "Foodland": {
      "costUnit": 94.6262,
      "costCase": 1419.3925,
      "gp": 0.25
    }
  },
  "4897024510396": {
    "Tops": {
      "costUnit": 92.1028,
      "costCase": 1381.5421,
      "gp": 0.27
    },
    "The Mall": {
      "costUnit": 100.9346,
      "costCase": 1514.0187,
      "gp": 0.2
    },
    "Homepro": {
      "costUnit": 94.6262,
      "costCase": 1419.3925,
      "gp": 0.25
    },
    "Big C": {
      "costUnit": 88.3178,
      "costCase": 1324.7664,
      "gp": 0.3
    },
    "Foodland": {
      "costUnit": 94.6262,
      "costCase": 1419.3925,
      "gp": 0.25
    }
  },
  "4897024516015": {
    "Tops": {
      "costUnit": 294.3925,
      "costCase": 1766.3551,
      "gp": 0.3
    },
    "Villa": {
      "costUnit": 315.4206,
      "costCase": 1892.5234,
      "gp": 0.25
    },
    "The Mall": {
      "costUnit": 336.4486,
      "costCase": 2018.6916,
      "gp": 0.2
    },
    "Homepro": {
      "costUnit": 315.4206,
      "costCase": 1892.5234,
      "gp": 0.25
    },
    "Big C": {
      "costUnit": 294.3925,
      "costCase": 1766.3551,
      "gp": 0.3
    },
    "Foodland": {
      "costUnit": 315.4206,
      "costCase": 1892.5234,
      "gp": 0.25
    }
  },
  "6901236388501": {
    "Tops": {
      "costUnit": 187.4766,
      "costCase": 2999.6262,
      "gp": 0.32
    },
    "Villa": {
      "costUnit": 206.7757,
      "costCase": 3308.4112,
      "gp": 0.25
    },
    "The Mall": {
      "costUnit": 220.5607,
      "costCase": 3528.972,
      "gp": 0.2
    },
    "Homepro": {
      "costUnit": 206.7757,
      "costCase": 3308.4112,
      "gp": 0.25
    },
    "Big C": {
      "costUnit": 192.9907,
      "costCase": 3087.8505,
      "gp": 0.3
    },
    "Foodland": {
      "costUnit": 206.7757,
      "costCase": 3308.4112,
      "gp": 0.25
    }
  },
  "4897024512697": {
    "Tops": {
      "costUnit": 201.2617,
      "costCase": 2012.6168,
      "gp": 0.27
    },
    "Homepro": {
      "costUnit": 206.7757,
      "costCase": 2067.757,
      "gp": 0.25
    },
    "Big C": {
      "costUnit": 206.7757,
      "costCase": 2067.757,
      "gp": 0.25
    },
    "Foodland": {
      "costUnit": 206.7757,
      "costCase": 2067.757,
      "gp": 0.25
    }
  },
  "6901236384855": {
    "Tops": {
      "costUnit": 115.6542,
      "costCase": 3469.6262,
      "gp": 0.25
    },
    "Villa": {
      "costUnit": 115.6542,
      "costCase": 3469.6262,
      "gp": 0.25
    },
    "Homepro": {
      "costUnit": 115.6542,
      "costCase": 3469.6262,
      "gp": 0.25
    },
    "Big C": {
      "costUnit": 115.6542,
      "costCase": 3469.6262,
      "gp": 0.25
    },
    "Foodland": {
      "costUnit": 115.6542,
      "costCase": 3469.6262,
      "gp": 0.25
    }
  },
  "6947509910086": {
    "Tops": {
      "costUnit": 115.6542,
      "costCase": 3469.6262,
      "gp": 0.25
    },
    "Villa": {
      "costUnit": 115.6542,
      "costCase": 3469.6262,
      "gp": 0.25
    },
    "Homepro": {
      "costUnit": 115.6542,
      "costCase": 3469.6262,
      "gp": 0.25
    },
    "Big C": {
      "costUnit": 115.6542,
      "costCase": 3469.6262,
      "gp": 0.25
    },
    "Foodland": {
      "costUnit": 115.6542,
      "costCase": 3469.6262,
      "gp": 0.25
    }
  },
  "5900785450005": {
    "Tops": {
      "costUnit": 101.6355,
      "costCase": 2032.7103,
      "gp": 0.25
    },
    "Villa": {
      "costUnit": 108.4112,
      "costCase": 2168.2243,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 107.0561,
      "costCase": 2141.1215,
      "gp": 0.21
    },
    "Homepro": {
      "costUnit": 104.3458,
      "costCase": 2086.9159,
      "gp": 0.23
    },
    "TWD": {
      "costUnit": 101.6355,
      "costCase": 2032.7103,
      "gp": 0.25
    },
    "Foodland": {
      "costUnit": 98.9252,
      "costCase": 1978.5047,
      "gp": 0.27
    }
  },
  "5900785450029": {
    "Tops": {
      "costUnit": 101.6355,
      "costCase": 2032.7103,
      "gp": 0.25
    },
    "Villa": {
      "costUnit": 108.4112,
      "costCase": 2168.2243,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 107.0561,
      "costCase": 2141.1215,
      "gp": 0.21
    },
    "Homepro": {
      "costUnit": 104.3458,
      "costCase": 2086.9159,
      "gp": 0.23
    },
    "TWD": {
      "costUnit": 101.6355,
      "costCase": 2032.7103,
      "gp": 0.25
    },
    "Foodland": {
      "costUnit": 98.9252,
      "costCase": 1978.5047,
      "gp": 0.27
    }
  },
  "5900785171092": {
    "Tops": {
      "costUnit": 94.6262,
      "costCase": 946.2617,
      "gp": 0.25
    },
    "Villa": {
      "costUnit": 100.9346,
      "costCase": 1009.3458,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 99.6729,
      "costCase": 996.729,
      "gp": 0.21
    },
    "Homepro": {
      "costUnit": 97.1495,
      "costCase": 971.4953,
      "gp": 0.23
    },
    "TWD": {
      "costUnit": 100.9346,
      "costCase": 1009.3458,
      "gp": 0.2
    }
  },
  "5900785171085": {
    "Tops": {
      "costUnit": 94.6262,
      "costCase": 946.2617,
      "gp": 0.25
    },
    "Villa": {
      "costUnit": 100.9346,
      "costCase": 1009.3458,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 99.6729,
      "costCase": 996.729,
      "gp": 0.21
    },
    "Homepro": {
      "costUnit": 97.1495,
      "costCase": 971.4953,
      "gp": 0.23
    },
    "TWD": {
      "costUnit": 100.9346,
      "costCase": 1009.3458,
      "gp": 0.2
    }
  },
  "3450601100406": {
    "Tops": {
      "costUnit": 97.5701,
      "costCase": 585.4206,
      "gp": 0.28
    }
  },
  "3450601100383": {
    "Tops": {
      "costUnit": 97.5701,
      "costCase": 585.4206,
      "gp": 0.28
    }
  },
  "3450601100413": {
    "Tops": {
      "costUnit": 97.5701,
      "costCase": 585.4206,
      "gp": 0.28
    }
  },
  "3450601100420": {
    "Tops": {
      "costUnit": 97.5701,
      "costCase": 585.4206,
      "gp": 0.28
    }
  },
  "017000024103": {
    "Tops": {
      "costUnit": 124.486,
      "costCase": 1493.8318,
      "gp": 0.28
    },
    "Villa": {
      "costUnit": 138.3178,
      "costCase": 1659.8131,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 134.86,
      "costCase": 2427.48,
      "gp": 0.22
    }
  },
  "011111014145": {
    "Tops": {
      "costUnit": 225.7009,
      "costCase": 1354.2056,
      "gp": 0.3
    },
    "The Mall": {
      "costUnit": 241.82,
      "costCase": 1450.92,
      "gp": 0.25
    },
    "Foodland": {
      "costUnit": 232.1495,
      "costCase": 1392.8972,
      "gp": 0.28
    },
    "Boots": {
      "costUnit": 225.7009,
      "costCase": 1354.2056,
      "gp": 0.3
    }
  },
  "011111014121": {
    "Tops": {
      "costUnit": 225.7009,
      "costCase": 1354.2056,
      "gp": 0.3
    },
    "The Mall": {
      "costUnit": 241.82,
      "costCase": 1450.92,
      "gp": 0.25
    },
    "Foodland": {
      "costUnit": 232.1495,
      "costCase": 1392.8972,
      "gp": 0.28
    },
    "Boots": {
      "costUnit": 225.7009,
      "costCase": 1354.2056,
      "gp": 0.3
    }
  },
  "011111014138": {
    "Tops": {
      "costUnit": 225.7009,
      "costCase": 1354.2056,
      "gp": 0.3
    },
    "The Mall": {
      "costUnit": 241.82,
      "costCase": 1450.92,
      "gp": 0.25
    },
    "Foodland": {
      "costUnit": 232.1495,
      "costCase": 1392.8972,
      "gp": 0.28
    },
    "Boots": {
      "costUnit": 225.7009,
      "costCase": 1354.2056,
      "gp": 0.3
    }
  },
  "011111614406": {
    "Tops": {
      "costUnit": 205.6075,
      "costCase": 3700.9346,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 192.76,
      "costCase": 3469.68,
      "gp": 0.25
    },
    "Lotus": {
      "costUnit": 167.0561,
      "costCase": 3007.0093,
      "gp": 0.35
    },
    "Big C": {
      "costUnit": 179.9065,
      "costCase": 3238.3178,
      "gp": 0.3
    },
    "Foodland": {
      "costUnit": 185.0467,
      "costCase": 3330.8411,
      "gp": 0.28
    }
  },
  "011111613300": {
    "Tops": {
      "costUnit": 205.6075,
      "costCase": 3700.9346,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 192.76,
      "costCase": 3469.68,
      "gp": 0.25
    },
    "Lotus": {
      "costUnit": 167.0561,
      "costCase": 3007.0093,
      "gp": 0.35
    },
    "Big C": {
      "costUnit": 179.9065,
      "costCase": 3238.3178,
      "gp": 0.3
    }
  },
  "011111615540": {
    "Tops": {
      "costUnit": 205.6075,
      "costCase": 3700.9346,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 192.76,
      "costCase": 3469.68,
      "gp": 0.25
    },
    "Lotus": {
      "costUnit": 167.0561,
      "costCase": 3007.0093,
      "gp": 0.35
    },
    "Big C": {
      "costUnit": 179.9065,
      "costCase": 3238.3178,
      "gp": 0.3
    }
  },
  "011111610699": {
    "Tops": {
      "costUnit": 205.6075,
      "costCase": 3700.9346,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 192.76,
      "costCase": 3469.68,
      "gp": 0.25
    },
    "Lotus": {
      "costUnit": 167.0561,
      "costCase": 3007.0093,
      "gp": 0.35
    },
    "Big C": {
      "costUnit": 179.9065,
      "costCase": 3238.3178,
      "gp": 0.3
    },
    "Foodland": {
      "costUnit": 185.0467,
      "costCase": 3330.8411,
      "gp": 0.28
    }
  },
  "8003510017386": {
    "Tops": {
      "costUnit": 192.9907,
      "costCase": 2315.8879,
      "gp": 0.3
    },
    "Villa": {
      "costUnit": 220.5607,
      "costCase": 2646.729,
      "gp": 0.2
    },
    "Lotus": {
      "costUnit": 179.2056,
      "costCase": 2150.4673,
      "gp": 0.35
    },
    "Big C": {
      "costUnit": 192.9907,
      "costCase": 2315.8879,
      "gp": 0.3
    },
    "Foodland": {
      "costUnit": 198.5047,
      "costCase": 2382.0561,
      "gp": 0.28
    }
  },
  "8003510009299": {
    "Tops": {
      "costUnit": 192.9907,
      "costCase": 2315.8879,
      "gp": 0.3
    },
    "Villa": {
      "costUnit": 220.5607,
      "costCase": 2646.729,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 206.7757,
      "costCase": 2481.3084,
      "gp": 0.25
    },
    "Lotus": {
      "costUnit": 179.2056,
      "costCase": 2150.4673,
      "gp": 0.35
    },
    "Big C": {
      "costUnit": 192.9907,
      "costCase": 2315.8879,
      "gp": 0.3
    },
    "Foodland": {
      "costUnit": 198.5047,
      "costCase": 2382.0561,
      "gp": 0.28
    }
  },
  "8003510026876": {
    "Tops": {
      "costUnit": 192.9907,
      "costCase": 2315.8879,
      "gp": 0.3
    },
    "Villa": {
      "costUnit": 220.5607,
      "costCase": 2646.729,
      "gp": 0.2
    },
    "Lotus": {
      "costUnit": 179.2056,
      "costCase": 2150.4673,
      "gp": 0.35
    },
    "Big C": {
      "costUnit": 192.9907,
      "costCase": 2315.8879,
      "gp": 0.3
    },
    "Foodland": {
      "costUnit": 198.5047,
      "costCase": 2382.0561,
      "gp": 0.28
    }
  },
  "8003510025107": {
    "Tops": {
      "costUnit": 192.9907,
      "costCase": 2315.8879,
      "gp": 0.3
    },
    "Villa": {
      "costUnit": 220.5607,
      "costCase": 2646.729,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 206.7757,
      "costCase": 2481.3084,
      "gp": 0.25
    },
    "Lotus": {
      "costUnit": 179.2056,
      "costCase": 2150.4673,
      "gp": 0.35
    },
    "Big C": {
      "costUnit": 192.9907,
      "costCase": 2315.8879,
      "gp": 0.3
    },
    "Foodland": {
      "costUnit": 198.5047,
      "costCase": 2382.0561,
      "gp": 0.28
    }
  },
  "8003510021581": {
    "Tops": {
      "costUnit": 136.6822,
      "costCase": 1640.1869,
      "gp": 0.25
    },
    "Villa": {
      "costUnit": 145.7944,
      "costCase": 1749.5327,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 136.6822,
      "costCase": 1640.1864,
      "gp": 0.25
    },
    "Lotus": {
      "costUnit": 118.4579,
      "costCase": 1421.4953,
      "gp": 0.35
    },
    "Big C": {
      "costUnit": 127.5701,
      "costCase": 1530.8411,
      "gp": 0.3
    }
  },
  "8003510019632": {
    "Tops": {
      "costUnit": 136.6822,
      "costCase": 1640.1869,
      "gp": 0.25
    },
    "Villa": {
      "costUnit": 145.7944,
      "costCase": 1749.5327,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 136.6822,
      "costCase": 1640.1864,
      "gp": 0.25
    },
    "Lotus": {
      "costUnit": 118.4579,
      "costCase": 1421.4953,
      "gp": 0.35
    },
    "Big C": {
      "costUnit": 127.5701,
      "costCase": 1530.8411,
      "gp": 0.3
    }
  },
  "8003510006274": {
    "Tops": {
      "costUnit": 136.6822,
      "costCase": 1640.1869,
      "gp": 0.25
    },
    "Villa": {
      "costUnit": 145.7944,
      "costCase": 1749.5327,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 136.6822,
      "costCase": 1640.1864,
      "gp": 0.25
    },
    "Lotus": {
      "costUnit": 118.4579,
      "costCase": 1421.4953,
      "gp": 0.35
    },
    "Big C": {
      "costUnit": 127.5701,
      "costCase": 1530.8411,
      "gp": 0.3
    }
  },
  "8901030545818": {
    "Tops": {
      "costUnit": 29.4393,
      "costCase": 1413.0841,
      "gp": 0.3
    },
    "The Mall": {
      "costUnit": 31.5421,
      "costCase": 1514.0187,
      "gp": 0.25
    },
    "Lotus": {
      "costUnit": 27.3364,
      "costCase": 1312.1495,
      "gp": 0.35
    },
    "Big C": {
      "costUnit": 29.4393,
      "costCase": 1413.0841,
      "gp": 0.3
    },
    "Foodland": {
      "costUnit": 31.5421,
      "costCase": 1514.0187,
      "gp": 0.25
    },
    "Boots": {
      "costUnit": 29.4393,
      "costCase": 1413.0841,
      "gp": 0.3
    }
  },
  "8901030545825": {
    "Tops": {
      "costUnit": 29.4393,
      "costCase": 1413.0841,
      "gp": 0.3
    },
    "The Mall": {
      "costUnit": 31.5421,
      "costCase": 1514.0187,
      "gp": 0.25
    },
    "Lotus": {
      "costUnit": 27.3364,
      "costCase": 1312.1495,
      "gp": 0.35
    },
    "Big C": {
      "costUnit": 29.4393,
      "costCase": 1413.0841,
      "gp": 0.3
    },
    "Foodland": {
      "costUnit": 31.5421,
      "costCase": 1514.0187,
      "gp": 0.25
    },
    "Boots": {
      "costUnit": 29.4393,
      "costCase": 1413.0841,
      "gp": 0.3
    }
  },
  "8901030026263": {
    "Tops": {
      "costUnit": 29.4393,
      "costCase": 1413.0841,
      "gp": 0.3
    },
    "The Mall": {
      "costUnit": 31.5421,
      "costCase": 1514.0187,
      "gp": 0.25
    },
    "Lotus": {
      "costUnit": 27.3364,
      "costCase": 1312.1495,
      "gp": 0.35
    },
    "Big C": {
      "costUnit": 29.4393,
      "costCase": 1413.0841,
      "gp": 0.3
    },
    "Foodland": {
      "costUnit": 31.5421,
      "costCase": 1514.0187,
      "gp": 0.25
    },
    "Boots": {
      "costUnit": 29.4393,
      "costCase": 1413.0841,
      "gp": 0.3
    }
  },
  "6281006485518": {
    "Tops": {
      "costUnit": 186.4486,
      "costCase": 2237.3832,
      "gp": 0.3
    },
    "The Mall": {
      "costUnit": 213.0841,
      "costCase": 2557.0093,
      "gp": 0.2
    },
    "Lotus": {
      "costUnit": 173.1308,
      "costCase": 2077.5701,
      "gp": 0.35
    },
    "Big C": {
      "costUnit": 186.4486,
      "costCase": 2237.3832,
      "gp": 0.3
    },
    "Boots": {
      "costUnit": 186.4486,
      "costCase": 2237.3832,
      "gp": 0.3
    }
  },
  "6281006485488": {
    "Tops": {
      "costUnit": 186.4486,
      "costCase": 2237.3832,
      "gp": 0.3
    },
    "The Mall": {
      "costUnit": 213.0841,
      "costCase": 2557.0093,
      "gp": 0.2
    },
    "Lotus": {
      "costUnit": 173.1308,
      "costCase": 2077.5701,
      "gp": 0.35
    },
    "Big C": {
      "costUnit": 186.4486,
      "costCase": 2237.3832,
      "gp": 0.3
    },
    "Boots": {
      "costUnit": 186.4486,
      "costCase": 2237.3832,
      "gp": 0.3
    }
  },
  "6281006485457": {
    "Tops": {
      "costUnit": 186.4486,
      "costCase": 2237.3832,
      "gp": 0.3
    },
    "The Mall": {
      "costUnit": 213.0841,
      "costCase": 2557.0093,
      "gp": 0.2
    },
    "Lotus": {
      "costUnit": 173.1308,
      "costCase": 2077.5701,
      "gp": 0.35
    },
    "Big C": {
      "costUnit": 186.4486,
      "costCase": 2237.3832,
      "gp": 0.3
    },
    "Boots": {
      "costUnit": 186.4486,
      "costCase": 2237.3832,
      "gp": 0.3
    }
  },
  "9369998073092": {
    "Tops": {
      "costUnit": 353.271,
      "costCase": 8478.5047,
      "gp": 0.28
    },
    "Villa": {
      "costUnit": 392.5234,
      "costCase": 9420.5607,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 367.9907,
      "costCase": 2207.9439,
      "gp": 0.25
    },
    "Lotus": {
      "costUnit": 318.9252,
      "costCase": 1913.5514,
      "gp": 0.35
    },
    "Foodland": {
      "costUnit": 358.1776,
      "costCase": 2149.0654,
      "gp": 0.27
    }
  },
  "9369998145553": {
    "Tops": {
      "costUnit": 353.271,
      "costCase": 8478.5047,
      "gp": 0.28
    },
    "Villa": {
      "costUnit": 392.5234,
      "costCase": 9420.5607,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 367.9907,
      "costCase": 2207.9439,
      "gp": 0.25
    },
    "Lotus": {
      "costUnit": 318.9252,
      "costCase": 1913.5514,
      "gp": 0.35
    },
    "Foodland": {
      "costUnit": 358.1776,
      "costCase": 2149.0654,
      "gp": 0.27
    }
  },
  "9358131000811": {
    "Tops": {
      "costUnit": 353.271,
      "costCase": 8478.5047,
      "gp": 0.28
    },
    "Villa": {
      "costUnit": 392.5234,
      "costCase": 9420.5607,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 367.9907,
      "costCase": 2207.9439,
      "gp": 0.25
    },
    "Lotus": {
      "costUnit": 318.9252,
      "costCase": 1913.5514,
      "gp": 0.35
    },
    "Foodland": {
      "costUnit": 358.1776,
      "costCase": 2149.0654,
      "gp": 0.27
    }
  },
  "9358131000057": {
    "Tops": {
      "costUnit": 353.271,
      "costCase": 8478.5047,
      "gp": 0.28
    },
    "Lotus": {
      "costUnit": 318.9252,
      "costCase": 1913.5514,
      "gp": 0.35
    }
  },
  "9358131000798": {
    "Tops": {
      "costUnit": 353.271,
      "costCase": 8478.5047,
      "gp": 0.28
    },
    "Lotus": {
      "costUnit": 318.9252,
      "costCase": 1913.5514,
      "gp": 0.35
    }
  },
  "9358131000507": {
    "Tops": {
      "costUnit": 353.271,
      "costCase": 8478.5047,
      "gp": 0.28
    },
    "Lotus": {
      "costUnit": 318.9252,
      "costCase": 1913.5514,
      "gp": 0.35
    }
  },
  "9358131000040": {
    "Tops": {
      "costUnit": 353.271,
      "costCase": 8478.5047,
      "gp": 0.28
    },
    "Villa": {
      "costUnit": 392.5234,
      "costCase": 9420.5607,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 367.9907,
      "costCase": 2207.9439,
      "gp": 0.25
    },
    "Lotus": {
      "costUnit": 318.9252,
      "costCase": 1913.5514,
      "gp": 0.35
    },
    "Foodland": {
      "costUnit": 358.1776,
      "costCase": 2149.0654,
      "gp": 0.27
    }
  },
  "9358131000491": {
    "Tops": {
      "costUnit": 353.271,
      "costCase": 8478.5047,
      "gp": 0.28
    },
    "The Mall": {
      "costUnit": 367.9907,
      "costCase": 2207.9439,
      "gp": 0.25
    },
    "Lotus": {
      "costUnit": 318.9252,
      "costCase": 1913.5514,
      "gp": 0.35
    },
    "Foodland": {
      "costUnit": 358.1776,
      "costCase": 2149.0654,
      "gp": 0.27
    }
  },
  "9358131000170": {
    "Tops": {
      "costUnit": 299.4393,
      "costCase": 7186.5421,
      "gp": 0.28
    },
    "Foodland": {
      "costUnit": 303.5981,
      "costCase": 1821.5888,
      "gp": 0.27
    }
  },
  "9358131000163": {
    "Tops": {
      "costUnit": 299.4393,
      "costCase": 7186.5421,
      "gp": 0.28
    },
    "Foodland": {
      "costUnit": 303.5981,
      "costCase": 1821.5888,
      "gp": 0.27
    }
  },
  "9358131000750": {
    "Tops": {
      "costUnit": 380.1869,
      "costCase": 9124.486,
      "gp": 0.28
    },
    "The Mall": {
      "costUnit": 396.028,
      "costCase": 2376.1682,
      "gp": 0.25
    },
    "Lotus": {
      "costUnit": 343.2243,
      "costCase": 2059.3458,
      "gp": 0.35
    }
  },
  "9358131000736": {
    "Tops": {
      "costUnit": 534.9533,
      "costCase": 12838.8785,
      "gp": 0.28
    },
    "Villa": {
      "costUnit": 594.3925,
      "costCase": 14265.4206,
      "gp": 0.2,
      "remark": "รออัพเดทจากจัดซื้อเรื่องจำนวนสาขาที่ได้วางอีกครั้ง"
    },
    "The Mall": {
      "costUnit": 557.243,
      "costCase": 3343.4579,
      "gp": 0.25
    },
    "Lotus": {
      "costUnit": 482.9439,
      "costCase": 2897.6636,
      "gp": 0.35
    }
  },
  "9358131001221": {
    "Tops": {
      "costUnit": 534.9533,
      "costCase": 12838.8785,
      "gp": 0.28
    },
    "Villa": {
      "costUnit": 594.3925,
      "costCase": 14265.4206,
      "gp": 0.2,
      "remark": "รออัพเดทจากจัดซื้อเรื่องจำนวนสาขาที่ได้วางอีกครั้ง"
    },
    "The Mall": {
      "costUnit": 557.243,
      "costCase": 3343.4579,
      "gp": 0.25
    },
    "Lotus": {
      "costUnit": 482.9439,
      "costCase": 2897.6636,
      "gp": 0.35
    }
  },
  "079400266552": {
    "Tops": {
      "costUnit": 245.3271,
      "costCase": 1471.9626,
      "gp": 0.3
    },
    "Foodland": {
      "costUnit": 252.3364,
      "costCase": 1514.0187,
      "gp": 0.28
    }
  },
  "079400266545": {
    "Tops": {
      "costUnit": 245.3271,
      "costCase": 1471.9626,
      "gp": 0.3
    },
    "Foodland": {
      "costUnit": 252.3364,
      "costCase": 1514.0187,
      "gp": 0.28
    }
  },
  "079400450258": {
    "Tops": {
      "costUnit": 245.3271,
      "costCase": 1471.9626,
      "gp": 0.3
    },
    "Foodland": {
      "costUnit": 252.3364,
      "costCase": 1514.0187,
      "gp": 0.28
    }
  },
  "9312657009017": {
    "Tops": {
      "costUnit": 191.7757,
      "costCase": 20711.7757,
      "gp": 0.28
    }
  },
  "9312657007013": {
    "Tops": {
      "costUnit": 191.7757,
      "costCase": 20711.7757,
      "gp": 0.28
    }
  },
  "9312657008010": {
    "Tops": {
      "costUnit": 191.7757,
      "costCase": 20711.7757,
      "gp": 0.28
    }
  },
  "9312657008027": {
    "Tops": {
      "costUnit": 191.7757,
      "costCase": 20711.7757,
      "gp": 0.28
    }
  },
  "9312657010013": {
    "Tops": {
      "costUnit": 191.7757,
      "costCase": 20711.7757,
      "gp": 0.28
    }
  },
  "9312657110201": {
    "Tops": {
      "costUnit": 400.3738,
      "costCase": 25623.9252,
      "gp": 0.28
    }
  },
  "9312657011225": {
    "Tops": {
      "costUnit": 198.5047,
      "costCase": 38112.8972,
      "gp": 0.28
    }
  },
  "9312657121122": {
    "Tops": {
      "costUnit": 198.5047,
      "costCase": 38112.8972,
      "gp": 0.28
    }
  },
  "9312657232316": {
    "Tops": {
      "costUnit": 191.7757,
      "costCase": 9205.2336,
      "gp": 0.28
    }
  },
  "9312657300220": {
    "Tops": {
      "costUnit": 400.3738,
      "costCase": 9608.972,
      "gp": 0.28
    }
  },
  "9312657300237": {
    "Tops": {
      "costUnit": 400.3738,
      "costCase": 9608.972,
      "gp": 0.28
    }
  },
  "4008239288158": {
    "Tops": {
      "costUnit": 74.1,
      "costCase": 592.8,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 73.15,
      "costCase": 585.2,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 66.5,
      "costCase": 532.0,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 88.785,
      "costCase": 710.2804
    },
    "Pet'n me": {
      "costUnit": 74.1,
      "costCase": 592.8,
      "gp": 0.22
    }
  },
  "4008239288134": {
    "Tops": {
      "costUnit": 74.1,
      "costCase": 592.8,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 73.15,
      "costCase": 585.2,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 66.5,
      "costCase": 532.0,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 88.785,
      "costCase": 710.2804
    },
    "Pet'n me": {
      "costUnit": 74.1,
      "costCase": 592.8,
      "gp": 0.22
    }
  },
  "4008239288141": {
    "Tops": {
      "costUnit": 74.1,
      "costCase": 592.8,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 73.15,
      "costCase": 585.2,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 66.5,
      "costCase": 532.0,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 88.785,
      "costCase": 710.2804
    },
    "Pet'n me": {
      "costUnit": 74.1,
      "costCase": 592.8,
      "gp": 0.22
    }
  },
  "4008239288110": {
    "Tops": {
      "costUnit": 74.1,
      "costCase": 592.8,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 73.15,
      "costCase": 585.2,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 66.5,
      "costCase": 532.0,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 88.785,
      "costCase": 710.2804
    },
    "Pet'n me": {
      "costUnit": 74.1,
      "costCase": 592.8,
      "gp": 0.22
    }
  },
  "4008239393159": {
    "Tops": {
      "costUnit": 74.1,
      "costCase": 592.8,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 73.15,
      "costCase": 585.2,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 88.785,
      "costCase": 710.2804
    },
    "Pet'n me": {
      "costUnit": 74.1,
      "costCase": 592.8,
      "gp": 0.22
    }
  },
  "4008239589057": {
    "Tops": {
      "costUnit": 66.3,
      "costCase": 1591.2,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 65.45,
      "costCase": 1570.8,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 369.1589,
      "costCase": 110747.6636
    },
    "Pet'n me": {
      "costUnit": 66.3,
      "costCase": 1591.2,
      "gp": 0.22
    }
  },
  "4008239589040": {
    "Tops": {
      "costUnit": 66.3,
      "costCase": 1591.2,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 65.45,
      "costCase": 1570.8,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 369.1589,
      "costCase": 110747.6636
    },
    "Pet'n me": {
      "costUnit": 66.3,
      "costCase": 1591.2,
      "gp": 0.22
    }
  },
  "4008239589033": {
    "Tops": {
      "costUnit": 66.3,
      "costCase": 1591.2,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 65.45,
      "costCase": 1570.8,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 369.1589,
      "costCase": 110747.6636
    },
    "Pet'n me": {
      "costUnit": 66.3,
      "costCase": 1591.2,
      "gp": 0.22
    }
  },
  "4008239587329": {
    "Tops": {
      "costUnit": 113.1,
      "costCase": 1244.1,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 111.65,
      "costCase": 1228.15,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 88.785,
      "costCase": 976.6355
    },
    "Pet'n me": {
      "costUnit": 113.1,
      "costCase": 1244.1,
      "gp": 0.22
    }
  },
  "4008239587336": {
    "Tops": {
      "costUnit": 113.1,
      "costCase": 1244.1,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 111.65,
      "costCase": 1228.15,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 88.785,
      "costCase": 976.6355
    },
    "Pet'n me": {
      "costUnit": 113.1,
      "costCase": 1244.1,
      "gp": 0.22
    }
  },
  "4008239589231": {
    "Tops": {
      "costUnit": 113.1,
      "costCase": 1244.1,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 111.65,
      "costCase": 1228.15,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 88.785,
      "costCase": 976.6355
    },
    "Pet'n me": {
      "costUnit": 113.1,
      "costCase": 1244.1,
      "gp": 0.22
    }
  },
  "4008239589248": {
    "Tops": {
      "costUnit": 113.1,
      "costCase": 1244.1,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 111.65,
      "costCase": 1228.15,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 88.785,
      "costCase": 976.6355
    },
    "Pet'n me": {
      "costUnit": 113.1,
      "costCase": 1244.1,
      "gp": 0.22
    }
  },
  "4008239288233": {
    "Tops": {
      "costUnit": 77.22,
      "costCase": 694.98,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 76.23,
      "costCase": 686.07,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 69.3,
      "costCase": 623.7,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 92.5234,
      "costCase": 832.7103
    },
    "Pet'n me": {
      "costUnit": 77.22,
      "costCase": 694.98,
      "gp": 0.22
    }
  },
  "4008239288219": {
    "Tops": {
      "costUnit": 77.22,
      "costCase": 694.98,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 76.23,
      "costCase": 686.07,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 69.3,
      "costCase": 623.7,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 92.5234,
      "costCase": 832.7103
    },
    "Pet'n me": {
      "costUnit": 77.22,
      "costCase": 694.98,
      "gp": 0.22
    }
  },
  "4008239315311": {
    "Tops": {
      "costUnit": 77.22,
      "costCase": 694.98,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 76.23,
      "costCase": 686.07,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 69.3,
      "costCase": 623.7,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 92.5234,
      "costCase": 832.7103
    },
    "Pet'n me": {
      "costUnit": 77.22,
      "costCase": 694.98,
      "gp": 0.22
    }
  },
  "4008239288226": {
    "Tops": {
      "costUnit": 77.22,
      "costCase": 694.98,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 76.23,
      "costCase": 686.07,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 69.3,
      "costCase": 623.7,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 92.5234,
      "costCase": 832.7103
    },
    "Pet'n me": {
      "costUnit": 77.22,
      "costCase": 694.98,
      "gp": 0.22
    }
  },
  "4008239398109": {
    "Tops": {
      "costUnit": 77.22,
      "costCase": 694.98,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 76.23,
      "costCase": 686.07,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 92.5234,
      "costCase": 832.7103
    },
    "Pet'n me": {
      "costUnit": 77.22,
      "costCase": 694.98,
      "gp": 0.22
    }
  },
  "4008239359445": {
    "Tops": {
      "costUnit": 58.5,
      "costCase": 1170.0,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 57.75,
      "costCase": 1155.0,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 51.4019,
      "costCase": 1028.0374
    },
    "Pet'n me": {
      "costUnit": 58.5,
      "costCase": 1170.0,
      "gp": 0.22
    }
  },
  "4008239359452": {
    "Tops": {
      "costUnit": 58.5,
      "costCase": 1170.0,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 57.75,
      "costCase": 1155.0,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 51.4019,
      "costCase": 1028.0374
    },
    "Pet'n me": {
      "costUnit": 58.5,
      "costCase": 1170.0,
      "gp": 0.22
    }
  },
  "4008239130440": {
    "Tops": {
      "costUnit": 58.5,
      "costCase": 1170.0,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 57.75,
      "costCase": 1155.0,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 51.4019,
      "costCase": 1028.0374
    },
    "Pet'n me": {
      "costUnit": 58.5,
      "costCase": 1170.0,
      "gp": 0.22
    }
  },
  "4008239359438": {
    "Tops": {
      "costUnit": 58.5,
      "costCase": 1170.0,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 57.75,
      "costCase": 1155.0,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 51.4019,
      "costCase": 1028.0374
    },
    "Pet'n me": {
      "costUnit": 58.5,
      "costCase": 1170.0,
      "gp": 0.22
    }
  },
  "4008239288196": {
    "Tops": {
      "costUnit": 113.1,
      "costCase": 1244.1,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 111.65,
      "costCase": 1228.15,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 101.5,
      "costCase": 1116.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 116.8224,
      "costCase": 1285.0467
    },
    "Pet'n me": {
      "costUnit": 113.1,
      "costCase": 1244.1,
      "gp": 0.22
    }
  },
  "4008239288189": {
    "Tops": {
      "costUnit": 113.1,
      "costCase": 1244.1,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 111.65,
      "costCase": 1228.15,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 101.5,
      "costCase": 1116.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 116.8224,
      "costCase": 1285.0467
    },
    "Pet'n me": {
      "costUnit": 113.1,
      "costCase": 1244.1,
      "gp": 0.22
    }
  },
  "4008239366627": {
    "Tops": {
      "costUnit": 35.1,
      "costCase": 807.3,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 34.65,
      "costCase": 796.95,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 31.5,
      "costCase": 724.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 42.0561,
      "costCase": 967.2897
    },
    "Pet'n me": {
      "costUnit": 35.1,
      "costCase": 807.3,
      "gp": 0.22
    }
  },
  "4008239366634": {
    "Tops": {
      "costUnit": 35.1,
      "costCase": 807.3,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 34.65,
      "costCase": 796.95,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 31.5,
      "costCase": 724.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 42.0561,
      "costCase": 967.2897
    },
    "Pet'n me": {
      "costUnit": 35.1,
      "costCase": 807.3,
      "gp": 0.22
    }
  },
  "4008239366658": {
    "Tops": {
      "costUnit": 35.1,
      "costCase": 807.3,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 34.65,
      "costCase": 796.95,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 31.5,
      "costCase": 724.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 42.0561,
      "costCase": 967.2897
    },
    "Pet'n me": {
      "costUnit": 35.1,
      "costCase": 807.3,
      "gp": 0.22
    }
  },
  "4008239366665": {
    "Tops": {
      "costUnit": 35.1,
      "costCase": 807.3,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 34.65,
      "costCase": 796.95,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 31.5,
      "costCase": 724.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 42.0561,
      "costCase": 967.2897
    },
    "Pet'n me": {
      "costUnit": 35.1,
      "costCase": 807.3,
      "gp": 0.22
    }
  },
  "4008239366689": {
    "Tops": {
      "costUnit": 35.1,
      "costCase": 807.3,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 34.65,
      "costCase": 796.95,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 31.5,
      "costCase": 724.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 42.0561,
      "costCase": 967.2897
    },
    "Pet'n me": {
      "costUnit": 35.1,
      "costCase": 807.3,
      "gp": 0.22
    }
  },
  "4008239366696": {
    "Tops": {
      "costUnit": 35.1,
      "costCase": 807.3,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 34.65,
      "costCase": 796.95,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 31.5,
      "costCase": 724.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 42.0561,
      "costCase": 967.2897
    },
    "Pet'n me": {
      "costUnit": 35.1,
      "costCase": 807.3,
      "gp": 0.22
    }
  },
  "4008239370266": {
    "Tops": {
      "costUnit": 38.22,
      "costCase": 573.3,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 37.73,
      "costCase": 565.95,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 34.3,
      "costCase": 514.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 45.7944,
      "costCase": 686.9159
    },
    "Pet'n me": {
      "costUnit": 38.22,
      "costCase": 573.3,
      "gp": 0.22
    }
  },
  "4008239370297": {
    "Tops": {
      "costUnit": 38.22,
      "costCase": 573.3,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 37.73,
      "costCase": 565.95,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 34.3,
      "costCase": 514.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 45.7944,
      "costCase": 686.9159
    },
    "Pet'n me": {
      "costUnit": 38.22,
      "costCase": 573.3,
      "gp": 0.22
    }
  },
  "4008239597212": {
    "Tops": {
      "costUnit": 38.22,
      "costCase": 573.3,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 37.73,
      "costCase": 565.95,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 34.3,
      "costCase": 514.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 45.7944,
      "costCase": 686.9159
    },
    "Pet'n me": {
      "costUnit": 38.22,
      "costCase": 573.3,
      "gp": 0.22
    }
  },
  "4008239370273": {
    "Tops": {
      "costUnit": 38.22,
      "costCase": 573.3,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 37.73,
      "costCase": 565.95,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 34.3,
      "costCase": 514.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 45.7944,
      "costCase": 686.9159
    },
    "Pet'n me": {
      "costUnit": 38.22,
      "costCase": 573.3,
      "gp": 0.22
    }
  },
  "4008239597229": {
    "Tops": {
      "costUnit": 38.22,
      "costCase": 573.3,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 37.73,
      "costCase": 565.95,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 34.3,
      "costCase": 514.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 45.7944,
      "costCase": 686.9159
    },
    "Pet'n me": {
      "costUnit": 38.22,
      "costCase": 573.3,
      "gp": 0.22
    }
  },
  "4008239370280": {
    "Tops": {
      "costUnit": 38.22,
      "costCase": 573.3,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 37.73,
      "costCase": 565.95,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 34.3,
      "costCase": 514.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 45.7944,
      "costCase": 686.9159
    },
    "Pet'n me": {
      "costUnit": 38.22,
      "costCase": 573.3,
      "gp": 0.22
    }
  },
  "4008239597205": {
    "Tops": {
      "costUnit": 38.22,
      "costCase": 573.3,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 37.73,
      "costCase": 565.95,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 34.3,
      "costCase": 514.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 45.7944,
      "costCase": 686.9159
    },
    "Pet'n me": {
      "costUnit": 38.22,
      "costCase": 573.3,
      "gp": 0.22
    }
  },
  "4008239597199": {
    "Tops": {
      "costUnit": 38.22,
      "costCase": 573.3,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 37.73,
      "costCase": 565.95,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 34.3,
      "costCase": 514.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 45.7944,
      "costCase": 686.9159
    },
    "Pet'n me": {
      "costUnit": 38.22,
      "costCase": 573.3,
      "gp": 0.22
    }
  },
  "4008239288080": {
    "Tops": {
      "costUnit": 152.1,
      "costCase": 912.6,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 150.15,
      "costCase": 900.9,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 136.5,
      "costCase": 819.0,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 135.514,
      "costCase": 813.0841
    },
    "Pet'n me": {
      "costUnit": 152.1,
      "costCase": 912.6,
      "gp": 0.22
    }
  },
  "4008239288073": {
    "Tops": {
      "costUnit": 152.1,
      "costCase": 912.6,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 150.15,
      "costCase": 900.9,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 136.5,
      "costCase": 819.0,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 135.514,
      "costCase": 813.0841
    },
    "Pet'n me": {
      "costUnit": 152.1,
      "costCase": 912.6,
      "gp": 0.22
    }
  },
  "4008239230096": {
    "Tops": {
      "costUnit": 35.1,
      "costCase": 1755.0,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 34.65,
      "costCase": 1732.5,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 42.0561,
      "costCase": 2102.8037
    },
    "Pet'n me": {
      "costUnit": 35.1,
      "costCase": 1755.0,
      "gp": 0.22
    }
  },
  "4008239231093": {
    "Tops": {
      "costUnit": 35.1,
      "costCase": 1755.0,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 34.65,
      "costCase": 1732.5,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 42.0561,
      "costCase": 2102.8037
    },
    "Pet'n me": {
      "costUnit": 35.1,
      "costCase": 1755.0,
      "gp": 0.22
    }
  },
  "4008239231109": {
    "Tops": {
      "costUnit": 35.1,
      "costCase": 1755.0,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 34.65,
      "costCase": 1732.5,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 42.0561,
      "costCase": 2102.8037
    },
    "Pet'n me": {
      "costUnit": 35.1,
      "costCase": 1755.0,
      "gp": 0.22
    }
  },
  "4008239288059": {
    "Tops": {
      "costUnit": 35.1,
      "costCase": 1755.0,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 34.65,
      "costCase": 1732.5,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 42.0561,
      "costCase": 2102.8037
    },
    "Pet'n me": {
      "costUnit": 35.1,
      "costCase": 1755.0,
      "gp": 0.22
    }
  },
  "4008239288042": {
    "Tops": {
      "costUnit": 42.9,
      "costCase": 2145.0,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 42.35,
      "costCase": 2117.5,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 51.4019,
      "costCase": 2570.0935
    },
    "Pet'n me": {
      "costUnit": 42.9,
      "costCase": 2145.0,
      "gp": 0.22
    }
  },
  "4008239587312": {
    "Tops": {
      "costUnit": 214.5,
      "costCase": 1930.5,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 211.75,
      "costCase": 1905.75,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 257.0093,
      "costCase": 2313.0841
    },
    "Pet'n me": {
      "costUnit": 214.5,
      "costCase": 1930.5,
      "gp": 0.22
    }
  },
  "4008239587305": {
    "Tops": {
      "costUnit": 214.5,
      "costCase": 1930.5,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 211.75,
      "costCase": 1905.75,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 257.0093,
      "costCase": 2313.0841
    },
    "Pet'n me": {
      "costUnit": 214.5,
      "costCase": 1930.5,
      "gp": 0.22
    }
  },
  "4008239234032": {
    "Tops": {
      "costUnit": 152.1,
      "costCase": 1825.2,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 150.15,
      "costCase": 1801.8,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 136.5,
      "costCase": 1638.0,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 163.5514,
      "costCase": 3925.2336
    },
    "Pet'n me": {
      "costUnit": 152.1,
      "costCase": 1825.2,
      "gp": 0.22
    }
  },
  "4008239230201": {
    "Tops": {
      "costUnit": 308.1,
      "costCase": 3697.2,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 304.15,
      "costCase": 3649.8,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 350.4673,
      "costCase": 4205.6075
    },
    "Pet'n me": {
      "costUnit": 308.1,
      "costCase": 3697.2,
      "gp": 0.22
    }
  },
  "4008239597243": {
    "Tops": {
      "costUnit": 46.02,
      "costCase": 690.3,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 45.43,
      "costCase": 681.45,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 41.3,
      "costCase": 619.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 45.7944,
      "costCase": 686.9159
    },
    "Pet'n me": {
      "costUnit": 46.02,
      "costCase": 690.3,
      "gp": 0.22
    }
  },
  "4008239597267": {
    "Tops": {
      "costUnit": 46.02,
      "costCase": 690.3,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 45.43,
      "costCase": 681.45,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 41.3,
      "costCase": 619.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 45.7944,
      "costCase": 686.9159
    },
    "Pet'n me": {
      "costUnit": 46.02,
      "costCase": 690.3,
      "gp": 0.22
    }
  },
  "4008239597250": {
    "Tops": {
      "costUnit": 46.02,
      "costCase": 690.3,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 45.43,
      "costCase": 681.45,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 41.3,
      "costCase": 619.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 45.7944,
      "costCase": 686.9159
    },
    "Pet'n me": {
      "costUnit": 46.02,
      "costCase": 690.3,
      "gp": 0.22
    }
  },
  "4008239597274": {
    "Tops": {
      "costUnit": 46.02,
      "costCase": 690.3,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 45.43,
      "costCase": 681.45,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 41.3,
      "costCase": 619.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 45.7944,
      "costCase": 686.9159
    },
    "Pet'n me": {
      "costUnit": 46.02,
      "costCase": 690.3,
      "gp": 0.22
    }
  },
  "4008239597281": {
    "Tops": {
      "costUnit": 46.02,
      "costCase": 690.3,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 45.43,
      "costCase": 681.45,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 41.3,
      "costCase": 619.5,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 45.7944,
      "costCase": 686.9159
    },
    "Pet'n me": {
      "costUnit": 46.02,
      "costCase": 690.3,
      "gp": 0.22
    }
  },
  "4008239250421": {
    "Tops": {
      "costUnit": 230.1,
      "costCase": 1380.6,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 227.15,
      "costCase": 1362.9,
      "gp": 0.23
    },
    "Pet'n me": {
      "costUnit": 230.1,
      "costCase": 1380.6,
      "gp": 0.22
    }
  },
  "4008239255839": {
    "Tops": {
      "costUnit": 113.1,
      "costCase": 678.6,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 134.75,
      "costCase": 808.5,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 101.5,
      "costCase": 609.0,
      "gp": 0.3
    },
    "Pet'n me": {
      "costUnit": 113.1,
      "costCase": 678.6,
      "gp": 0.22
    }
  },
  "4008239255846": {
    "Tops": {
      "costUnit": 222.3,
      "costCase": 1111.5,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 219.45,
      "costCase": 1097.25,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 199.5,
      "costCase": 997.5,
      "gp": 0.3
    },
    "Pet'n me": {
      "costUnit": 222.3,
      "costCase": 1111.5,
      "gp": 0.22
    }
  },
  "4008239292223": {
    "Tops": {
      "costUnit": 113.1,
      "costCase": 678.6,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 111.65,
      "costCase": 669.9,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 101.5,
      "costCase": 609.0,
      "gp": 0.3
    },
    "Pet'n me": {
      "costUnit": 113.1,
      "costCase": 678.6,
      "gp": 0.22
    }
  },
  "4008239314628": {
    "Tops": {
      "costUnit": 308.1,
      "costCase": 1540.5,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 304.15,
      "costCase": 1520.75,
      "gp": 0.23
    },
    "Pet'n me": {
      "costUnit": 308.1,
      "costCase": 1540.5,
      "gp": 0.22
    }
  },
  "4008239257475": {
    "Tops": {
      "costUnit": 113.1,
      "costCase": 565.5,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 111.65,
      "costCase": 558.25,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 101.5,
      "costCase": 507.5,
      "gp": 0.3
    },
    "Pet'n me": {
      "costUnit": 113.1,
      "costCase": 565.5,
      "gp": 0.22
    }
  },
  "4008239257482": {
    "Tops": {
      "costUnit": 113.1,
      "costCase": 565.5,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 111.65,
      "costCase": 558.25,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 101.5,
      "costCase": 507.5,
      "gp": 0.3
    },
    "Pet'n me": {
      "costUnit": 113.1,
      "costCase": 565.5,
      "gp": 0.22
    }
  },
  "4008239257499": {
    "Tops": {
      "costUnit": 113.1,
      "costCase": 565.5,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 111.65,
      "costCase": 558.25,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 101.5,
      "costCase": 507.5,
      "gp": 0.3
    },
    "Pet'n me": {
      "costUnit": 113.1,
      "costCase": 565.5,
      "gp": 0.22
    }
  },
  "4008239257505": {
    "Tops": {
      "costUnit": 113.1,
      "costCase": 565.5,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 111.65,
      "costCase": 558.25,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 101.5,
      "costCase": 507.5,
      "gp": 0.3
    },
    "Pet'n me": {
      "costUnit": 113.1,
      "costCase": 565.5,
      "gp": 0.22
    }
  },
  "4008239257796": {
    "Tops": {
      "costUnit": 113.1,
      "costCase": 565.5,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 111.65,
      "costCase": 558.25,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 101.5,
      "costCase": 507.5,
      "gp": 0.3
    },
    "Pet'n me": {
      "costUnit": 113.1,
      "costCase": 565.5,
      "gp": 0.22
    }
  },
  "4008239255426": {
    "Tops": {
      "costUnit": 663.0,
      "costCase": 2652.0,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 654.5,
      "costCase": 2618.0,
      "gp": 0.23
    },
    "Pet'n me": {
      "costUnit": 663.0,
      "costCase": 2652.0,
      "gp": 0.22
    }
  },
  "4008239255815": {
    "Tops": {
      "costUnit": 144.3,
      "costCase": 865.8,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 142.45,
      "costCase": 854.7,
      "gp": 0.23
    },
    "Pet'n me": {
      "costUnit": 144.3,
      "costCase": 865.8,
      "gp": 0.22
    }
  },
  "4008239314550": {
    "Tops": {
      "costUnit": 308.1,
      "costCase": 1540.5,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 304.15,
      "costCase": 1520.75,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 276.5,
      "costCase": 1382.5,
      "gp": 0.3
    },
    "Pet'n me": {
      "costUnit": 308.1,
      "costCase": 1540.5,
      "gp": 0.22
    }
  },
  "4008239314567": {
    "Tops": {
      "costUnit": 663.0,
      "costCase": 3315.0,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 654.5,
      "costCase": 3272.5,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 595.0,
      "costCase": 2975.0,
      "gp": 0.3
    },
    "Pet'n me": {
      "costUnit": 663.0,
      "costCase": 3315.0,
      "gp": 0.22
    }
  },
  "4008239257451": {
    "Tops": {
      "costUnit": 113.1,
      "costCase": 565.5,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 111.65,
      "costCase": 558.25,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 101.5,
      "costCase": 507.5,
      "gp": 0.3
    },
    "Pet'n me": {
      "costUnit": 113.1,
      "costCase": 565.5,
      "gp": 0.22
    }
  },
  "4008239216410": {
    "Tops": {
      "costUnit": 308.1,
      "costCase": 1540.5,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 304.15,
      "costCase": 1520.75,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 276.5,
      "costCase": 11336.5,
      "gp": 0.3
    },
    "Pet'n me": {
      "costUnit": 308.1,
      "costCase": 1540.5,
      "gp": 0.22
    }
  },
  "4008239216434": {
    "Tops": {
      "costUnit": 308.1,
      "costCase": 1540.5,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 304.15,
      "costCase": 1520.75,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 276.5,
      "costCase": 11613.0,
      "gp": 0.3
    },
    "Pet'n me": {
      "costUnit": 308.1,
      "costCase": 1540.5,
      "gp": 0.22
    }
  },
  "4008239216441": {
    "Tops": {
      "costUnit": 308.1,
      "costCase": 1540.5,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 304.15,
      "costCase": 1520.75,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 276.5,
      "costCase": 11889.5,
      "gp": 0.3
    },
    "Pet'n me": {
      "costUnit": 308.1,
      "costCase": 1540.5,
      "gp": 0.22
    }
  },
  "4008239214812": {
    "Tops": {
      "costUnit": 230.1,
      "costCase": 1150.5,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 227.15,
      "costCase": 1135.75,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 206.5,
      "costCase": 1032.5,
      "gp": 0.3
    },
    "Pet'n me": {
      "costUnit": 230.1,
      "costCase": 1150.5,
      "gp": 0.22
    }
  },
  "4008239214843": {
    "Tops": {
      "costUnit": 230.1,
      "costCase": 1150.5,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 227.15,
      "costCase": 1135.75,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 206.5,
      "costCase": 1032.5,
      "gp": 0.3
    },
    "Pet'n me": {
      "costUnit": 230.1,
      "costCase": 1150.5,
      "gp": 0.22
    }
  },
  "4008239214805": {
    "Tops": {
      "costUnit": 230.1,
      "costCase": 1150.5,
      "gp": 0.22
    },
    "Villa": {
      "costUnit": 227.15,
      "costCase": 1135.75,
      "gp": 0.23
    },
    "Pet'n me": {
      "costUnit": 230.1,
      "costCase": 1150.5,
      "gp": 0.22
    }
  },
  "4000530701527": {
    "Tops": {
      "costUnit": 4030.3738,
      "gp": 0.25
    },
    "Homepro": {
      "costUnit": 5560.7477,
      "costCase": 5560.7477,
      "gp": 0.3
    },
    "Central Department": {
      "costUnit": 4575.7,
      "gp": 0.28
    }
  },
  "4000530649607": {
    "Tops": {
      "costUnit": 1086.4486,
      "gp": 0.25
    },
    "Homepro": {
      "costUnit": 1733.6449,
      "costCase": 1733.6449,
      "gp": 0.3
    },
    "Central Department": {
      "costUnit": 1609.8131,
      "gp": 0.35
    }
  },
  "4000530649614": {
    "Tops": {
      "costUnit": 1296.729,
      "gp": 0.25
    },
    "Homepro": {
      "costUnit": 2348.5981,
      "costCase": 2348.5981,
      "gp": 0.3
    },
    "Central Department": {
      "costUnit": 2180.8411,
      "gp": 0.35
    }
  },
  "4000530681225": {
    "Tops": {
      "costUnit": 3189.2523,
      "gp": 0.25
    },
    "Homepro": {
      "costUnit": 5855.1402,
      "costCase": 5855.1402,
      "gp": 0.3
    }
  },
  "4000530597748": {
    "Tops": {
      "costUnit": 665.8879,
      "gp": 0.25
    },
    "Central Department": {
      "costUnit": 6594.39,
      "gp": 0.28
    }
  },
  "4000530680280": {
    "Tops": {
      "costUnit": 771.028,
      "gp": 0.25
    },
    "Central Department": {
      "costUnit": 1391.1215,
      "gp": 0.35
    }
  },
  "4000530679826": {
    "Tops": {
      "costUnit": 455.6075,
      "gp": 0.25
    }
  },
  "5900785171511": {
    "Villa": {
      "costUnit": 100.9346,
      "costCase": 1211.215,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 99.6729,
      "costCase": 1196.0748,
      "gp": 0.21
    },
    "Homepro": {
      "costUnit": 97.1495,
      "costCase": 1165.7944,
      "gp": 0.23
    },
    "TWD": {
      "costUnit": 100.9346,
      "costCase": 1211.215,
      "gp": 0.2
    },
    "Foodland": {
      "costUnit": 92.1028,
      "costCase": 1105.2336,
      "gp": 0.27
    }
  },
  "5900785171542": {
    "Villa": {
      "costUnit": 100.9346,
      "costCase": 1211.215,
      "gp": 0.2
    },
    "The Mall": {
      "costUnit": 99.6729,
      "costCase": 1196.0748,
      "gp": 0.21
    },
    "Homepro": {
      "costUnit": 97.1495,
      "costCase": 1165.7944,
      "gp": 0.23
    },
    "TWD": {
      "costUnit": 94.6262,
      "costCase": 1135.514,
      "gp": 0.25
    }
  },
  "4015000310048": {
    "Villa": {
      "costUnit": 201.2617,
      "costCase": 2012.6168,
      "gp": 0.27
    },
    "Lotus": {
      "costUnit": 192.99,
      "costCase": 1929.91,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 220.56,
      "costCase": 2205.6,
      "gp": 0.3
    },
    "TWD": {
      "costUnit": 220.5607,
      "costCase": 2205.6075,
      "gp": 0.2
    }
  },
  "8003510010837": {
    "Villa": {
      "costUnit": 108.4112,
      "costCase": 1300.9346,
      "gp": 0.2
    },
    "Foodland": {
      "costUnit": 97.5701,
      "costCase": 1170.8411,
      "gp": 0.28
    }
  },
  "8003510016501": {
    "Villa": {
      "costUnit": 108.4112,
      "costCase": 1300.9346,
      "gp": 0.2
    },
    "Foodland": {
      "costUnit": 97.5701,
      "costCase": 1170.8411,
      "gp": 0.28
    }
  },
  "8003510021840": {
    "Villa": {
      "costUnit": 108.4112,
      "costCase": 1300.9346,
      "gp": 0.2
    },
    "Foodland": {
      "costUnit": 97.5701,
      "costCase": 1170.8411,
      "gp": 0.28
    }
  },
  "8003510010899": {
    "Villa": {
      "costUnit": 108.4112,
      "costCase": 1300.9346,
      "gp": 0.2
    },
    "Foodland": {
      "costUnit": 97.5701,
      "costCase": 1170.8411,
      "gp": 0.28
    }
  },
  "9358131001658": {
    "Villa": {
      "costUnit": 392.5234,
      "costCase": 9420.5607,
      "gp": 0.2,
      "remark": "สินค้า Seasonal วางขายช่วงเดือนกันยายน"
    }
  },
  "9358131001276": {
    "Villa": {
      "costUnit": 392.5234,
      "costCase": 9420.5607,
      "gp": 0.2,
      "remark": "สินค้า Seasonal วางขายช่วงเดือนกันยายน"
    }
  },
  "9358131001535": {
    "Villa": {
      "costUnit": 392.5234,
      "costCase": 9420.5607,
      "gp": 0.2,
      "remark": "สินค้า Seasonal วางขายช่วงเดือนกันยายน"
    }
  },
  "9358131001498": {
    "Villa": {
      "costUnit": 392.5234,
      "costCase": 9420.5607,
      "gp": 0.2,
      "remark": "สินค้า Seasonal วางขายช่วงเดือนกันยายน"
    }
  },
  "4008239359537": {
    "Villa": {
      "costUnit": 26.95,
      "costCase": 1293.6,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 24.5,
      "costCase": 1176.0,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 32.7103,
      "costCase": 1570.0935
    },
    "Pet'n me": {
      "costUnit": 27.3,
      "costCase": 1310.4,
      "gp": 0.22
    }
  },
  "4008239359544": {
    "Villa": {
      "costUnit": 26.95,
      "costCase": 1293.6,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 24.5,
      "costCase": 1176.0,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 32.7103,
      "costCase": 1570.0935
    },
    "Pet'n me": {
      "costUnit": 27.3,
      "costCase": 1310.4,
      "gp": 0.22
    }
  },
  "4008239359520": {
    "Villa": {
      "costUnit": 26.95,
      "costCase": 1293.6,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 24.5,
      "costCase": 1176.0,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 32.7103,
      "costCase": 1570.0935
    },
    "Pet'n me": {
      "costUnit": 27.3,
      "costCase": 1310.4,
      "gp": 0.22
    }
  },
  "4008239359575": {
    "Villa": {
      "costUnit": 26.95,
      "costCase": 1293.6,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 24.5,
      "costCase": 1176.0,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 32.7103,
      "costCase": 1570.0935
    },
    "Pet'n me": {
      "costUnit": 27.3,
      "costCase": 1310.4,
      "gp": 0.22
    }
  },
  "4008239359551": {
    "Villa": {
      "costUnit": 26.95,
      "costCase": 1293.6,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 24.5,
      "costCase": 1176.0,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 32.7103,
      "costCase": 1570.0935
    },
    "Pet'n me": {
      "costUnit": 27.3,
      "costCase": 1310.4,
      "gp": 0.22
    }
  },
  "4008239359568": {
    "Villa": {
      "costUnit": 26.95,
      "costCase": 1293.6,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 24.5,
      "costCase": 1176.0,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 32.7103,
      "costCase": 1570.0935
    },
    "Pet'n me": {
      "costUnit": 27.3,
      "costCase": 1310.4,
      "gp": 0.22
    }
  },
  "4008239230195": {
    "Villa": {
      "costUnit": 288.75,
      "costCase": 1732.5,
      "gp": 0.23
    },
    "Lotus": {
      "costUnit": 262.5,
      "costCase": 1575.0,
      "gp": 0.3
    },
    "Homepro": {
      "costUnit": 327.1028,
      "costCase": 1962.6168
    },
    "Pet'n me": {
      "costUnit": 292.5,
      "costCase": 1755.0,
      "gp": 0.22
    }
  },
  "4008239308740": {
    "Villa": {
      "costUnit": 288.75,
      "costCase": 1732.5,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 327.1028,
      "costCase": 1962.6168
    },
    "Pet'n me": {
      "costUnit": 292.5,
      "costCase": 1755.0,
      "gp": 0.22
    }
  },
  "019800036676": {
    "The Mall": {
      "costUnit": 74.0183,
      "costCase": 888.22,
      "gp": 0.2
    },
    "Homepro": {
      "costUnit": 70.3122,
      "costCase": 843.747,
      "gp": 0.2401
    },
    "Foodland": {
      "costUnit": 74.0187,
      "costCase": 888.2243,
      "gp": 0.2
    }
  },
  "019800036638": {
    "The Mall": {
      "costUnit": 74.0183,
      "costCase": 888.22,
      "gp": 0.2
    },
    "Big C": {
      "costUnit": 66.62,
      "costCase": 799.44,
      "gp": 0.28
    }
  },
  "019800036614": {
    "The Mall": {
      "costUnit": 74.0183,
      "costCase": 888.22,
      "gp": 0.2
    },
    "Homepro": {
      "costUnit": 70.3122,
      "costCase": 843.747,
      "gp": 0.2401
    },
    "Big C": {
      "costUnit": 71.3022,
      "costCase": 855.627,
      "gp": 0.2294
    },
    "Foodland": {
      "costUnit": 74.0187,
      "costCase": 888.2243,
      "gp": 0.2
    }
  },
  "023400053605": {
    "The Mall": {
      "costUnit": 74.0183,
      "costCase": 888.22,
      "gp": 0.2
    }
  },
  "023400998081": {
    "The Mall": {
      "costUnit": 74.0183,
      "costCase": 888.22,
      "gp": 0.2
    }
  },
  "023400000630": {
    "The Mall": {
      "costUnit": 74.0183,
      "costCase": 888.22,
      "gp": 0.2
    }
  },
  "023400010677": {
    "The Mall": {
      "costUnit": 71.24,
      "costCase": 854.88,
      "gp": 0.23
    },
    "Homepro": {
      "costUnit": 71.24,
      "costCase": 854.88,
      "gp": 0.23
    }
  },
  "4015000966214": {
    "The Mall": {
      "costUnit": 395.0,
      "costCase": 2370.0,
      "gp": 0.21
    },
    "Big C": {
      "costUnit": 400.0,
      "costCase": 2400.0,
      "gp": 0.2
    }
  },
  "4015000312400": {
    "The Mall": {
      "costUnit": 395.0,
      "costCase": 2370.0,
      "gp": 0.21
    },
    "Big C": {
      "costUnit": 400.0,
      "costCase": 2400.0,
      "gp": 0.2
    },
    "Foodland": {
      "costUnit": 400.0,
      "costCase": 2400.0,
      "gp": 0.2
    }
  },
  "4015000318129": {
    "The Mall": {
      "costUnit": 291.63,
      "costCase": 2333.08,
      "gp": 0.21
    },
    "Big C": {
      "costUnit": 306.4,
      "costCase": 2451.21,
      "gp": 0.17
    },
    "Foodland": {
      "costUnit": 295.327,
      "costCase": 2362.66,
      "gp": 0.2
    }
  },
  "4015000308786": {
    "The Mall": {
      "costUnit": 291.63,
      "costCase": 2333.08,
      "gp": 0.21
    },
    "Big C": {
      "costUnit": 306.4,
      "costCase": 2451.21,
      "gp": 0.17
    },
    "Foodland": {
      "costUnit": 295.327,
      "costCase": 2362.66,
      "gp": 0.2
    }
  },
  "4015000312929": {
    "The Mall": {
      "costUnit": 291.63,
      "costCase": 2333.08,
      "gp": 0.21
    },
    "Big C": {
      "costUnit": 267.6168,
      "costCase": 2140.9346,
      "gp": 0.17
    }
  },
  "4015000318167": {
    "The Mall": {
      "costUnit": 136.59,
      "costCase": 1639.06,
      "gp": 0.21
    },
    "Homepro": {
      "costUnit": 138.3178,
      "costCase": 1659.8131,
      "gp": 0.2
    },
    "Big C": {
      "costUnit": 118.785,
      "costCase": 1425.4206,
      "gp": 0.18
    }
  },
  "024200097813": {
    "The Mall": {
      "costUnit": 295.33,
      "costCase": 1771.98,
      "gp": 0.2
    },
    "Big C": {
      "costUnit": 295.3271,
      "costCase": 1771.9626,
      "gp": 0.2
    }
  },
  "024200047849": {
    "The Mall": {
      "costUnit": 272.0567,
      "costCase": 1632.34,
      "gp": 0.18
    },
    "Big C": {
      "costUnit": 265.4206,
      "costCase": 1592.5234,
      "gp": 0.2
    },
    "Foodland": {
      "costUnit": 265.42,
      "costCase": 1592.52,
      "gp": 0.2
    }
  },
  "024200047887": {
    "The Mall": {
      "costUnit": 272.0567,
      "costCase": 1632.34,
      "gp": 0.18
    },
    "Big C": {
      "costUnit": 265.4206,
      "costCase": 1592.5234,
      "gp": 0.2
    }
  },
  "024200060220": {
    "The Mall": {
      "costUnit": 295.0467,
      "costCase": 1770.28,
      "gp": 0.18
    },
    "Big C": {
      "costUnit": 287.8505,
      "costCase": 1727.1028,
      "gp": 0.2
    }
  },
  "024200003005": {
    "The Mall": {
      "costUnit": 272.0567,
      "costCase": 1632.34,
      "gp": 0.18
    },
    "Big C": {
      "costUnit": 265.4206,
      "costCase": 1592.5234,
      "gp": 0.2
    },
    "Foodland": {
      "costUnit": 265.42,
      "costCase": 1592.52,
      "gp": 0.2
    }
  },
  "4015000318198": {
    "The Mall": {
      "costUnit": 175.5,
      "costCase": 1404.0,
      "gp": 0.275
    },
    "Homepro": {
      "costUnit": 169.4393,
      "costCase": 1355.514,
      "gp": 0.3
    },
    "Big C": {
      "costUnit": 181.5421,
      "costCase": 1452.3364,
      "gp": 0.25
    },
    "Foodland": {
      "costUnit": 198.49,
      "costCase": 1587.92,
      "gp": 0.18
    }
  },
  "4015000313681": {
    "The Mall": {
      "costUnit": 415.0,
      "costCase": 3320.0,
      "gp": 0.2537
    },
    "Homepro": {
      "costUnit": 389.2523,
      "costCase": 3114.0187,
      "gp": 0.3
    },
    "Big C": {
      "costUnit": 455.6075,
      "costCase": 3644.8598,
      "gp": 0.25
    },
    "Foodland": {
      "costUnit": 455.98,
      "costCase": 3647.84,
      "gp": 0.18
    }
  },
  "4015000314374": {
    "The Mall": {
      "costUnit": 169.1,
      "costCase": 2705.6,
      "gp": 0.2301
    },
    "Homepro": {
      "costUnit": 175.7009,
      "costCase": 2811.215,
      "gp": 0.2
    }
  },
  "8809004773819": {
    "The Mall": {
      "costUnit": 99.673,
      "costCase": 996.73,
      "gp": 0.21
    },
    "Homepro": {
      "costUnit": 97.1495,
      "costCase": 971.4953,
      "gp": 0.23
    },
    "Big C": {
      "costUnit": 97.1495,
      "costCase": 971.4953,
      "gp": 0.23
    }
  },
  "8809004773826": {
    "The Mall": {
      "costUnit": 99.673,
      "costCase": 996.73,
      "gp": 0.21
    },
    "Homepro": {
      "costUnit": 97.1495,
      "costCase": 971.4953,
      "gp": 0.23
    },
    "Big C": {
      "costUnit": 97.1495,
      "costCase": 971.4953,
      "gp": 0.23
    }
  },
  "8809004773802": {
    "The Mall": {
      "costUnit": 99.673,
      "costCase": 996.73,
      "gp": 0.21
    },
    "Homepro": {
      "costUnit": 97.1495,
      "costCase": 971.4953,
      "gp": 0.23
    },
    "Big C": {
      "costUnit": 97.1495,
      "costCase": 971.4953,
      "gp": 0.23
    },
    "Foodland": {
      "costUnit": 100.44,
      "costCase": 1004.4,
      "gp": 0.2039
    }
  },
  "017000024028": {
    "The Mall": {
      "costUnit": 134.86,
      "costCase": 2427.48,
      "gp": 0.22
    },
    "Foodland": {
      "costUnit": 141.77,
      "costCase": 2551.96,
      "gp": 0.18
    }
  },
  "4800096476705": {
    "The Mall": {
      "costUnit": 410.0467,
      "costCase": 2460.2804,
      "gp": 0.25
    }
  },
  "4800096476712": {
    "The Mall": {
      "costUnit": 473.1308,
      "costCase": 2838.785,
      "gp": 0.25
    }
  },
  "7322540592412": {
    "The Mall": {
      "costUnit": 389.0187,
      "costCase": 2334.1121,
      "gp": 0.25
    }
  },
  "7322540574876": {
    "The Mall": {
      "costUnit": 389.0187,
      "costCase": 2334.1121,
      "gp": 0.25
    }
  },
  "9557327029401": {
    "The Mall": {
      "costUnit": 571.2617,
      "costCase": 4570.0935,
      "gp": 0.25
    }
  },
  "9557327029418": {
    "The Mall": {
      "costUnit": 571.2617,
      "costCase": 4570.0935,
      "gp": 0.25
    }
  },
  "023400006557": {
    "The Mall": {
      "costUnit": 74.0183,
      "costCase": 888.22,
      "gp": 0.2
    }
  },
  "017000018409": {
    "The Mall": {
      "costUnit": 134.86,
      "costCase": 2427.48,
      "gp": 0.22
    },
    "Lotus": {
      "costUnit": 94.16,
      "costCase": 1694.86,
      "gp": 0.35
    }
  },
  "6901236388518": {
    "The Mall": {
      "costUnit": 220.5607,
      "costCase": 3528.972,
      "gp": 0.2
    },
    "Homepro": {
      "costUnit": 206.7757,
      "costCase": 3308.4112,
      "gp": 0.25
    },
    "Big C": {
      "costUnit": 192.9907,
      "costCase": 3087.8505,
      "gp": 0.3
    },
    "Foodland": {
      "costUnit": 206.7757,
      "costCase": 3308.4112,
      "gp": 0.25
    }
  },
  "0011111014121": {
    "Lotus": {
      "costUnit": 209.5794,
      "costCase": 1257.4766,
      "gp": 0.35
    },
    "Big C": {
      "costUnit": 225.7009,
      "costCase": 1354.2056,
      "gp": 0.3
    }
  },
  "0011111014145": {
    "Lotus": {
      "costUnit": 209.5794,
      "costCase": 1257.4766,
      "gp": 0.35
    },
    "Big C": {
      "costUnit": 225.7009,
      "costCase": 1354.2056,
      "gp": 0.3
    }
  },
  "0011111014138": {
    "Lotus": {
      "costUnit": 209.5794,
      "costCase": 1257.4766,
      "gp": 0.35
    },
    "Big C": {
      "costUnit": 225.7009,
      "costCase": 1354.2056,
      "gp": 0.3
    }
  },
  "023400000982": {
    "Homepro": {
      "costUnit": 70.3178,
      "costCase": 843.8131,
      "gp": 0.24
    },
    "Big C": {
      "costUnit": 66.62,
      "costCase": 799.44,
      "gp": 0.28
    },
    "Foodland": {
      "costUnit": 74.0187,
      "costCase": 888.2243,
      "gp": 0.2
    }
  },
  "023400350001": {
    "Homepro": {
      "costUnit": 70.3178,
      "costCase": 843.8131,
      "gp": 0.24
    },
    "Big C": {
      "costUnit": 66.62,
      "costCase": 799.44,
      "gp": 0.28
    },
    "Foodland": {
      "costUnit": 74.0187,
      "costCase": 888.2243,
      "gp": 0.2
    }
  },
  "023400061563": {
    "Homepro": {
      "costUnit": 209.5327,
      "costCase": 838.1308,
      "gp": 0.24
    },
    "Big C": {
      "costUnit": 198.5,
      "costCase": 794.0,
      "gp": 0.28
    }
  },
  "9350376001806": {
    "Homepro": {
      "costUnit": 97.1495,
      "costCase": 582.8972,
      "gp": 0.23
    }
  },
  "023400016020": {
    "Homepro": {
      "costUnit": 175.7009,
      "costCase": 1581.3084,
      "gp": 0.2
    },
    "Big C": {
      "costUnit": 175.7,
      "costCase": 1581.3,
      "gp": 0.2
    }
  },
  "4015000309042": {
    "Homepro": {
      "costUnit": 145.7944,
      "costCase": 1749.5327,
      "gp": 0.2
    },
    "Big C": {
      "costUnit": 121.8224,
      "costCase": 1461.8692,
      "gp": 0.21
    }
  },
  "4008239393166": {
    "Homepro": {
      "costUnit": 88.785,
      "costCase": 710.2804
    }
  },
  "4008239594709": {
    "Homepro": {
      "costUnit": 140.1869,
      "costCase": 1542.0561
    }
  },
  "4008239594716": {
    "Homepro": {
      "costUnit": 140.1869,
      "costCase": 1542.0561
    }
  },
  "4008239400307": {
    "Homepro": {
      "costUnit": 51.4019,
      "costCase": 1028.0374
    }
  },
  "4008239595690": {
    "Homepro": {
      "costUnit": 70.0935,
      "costCase": 1401.8692
    }
  },
  "4008239595706": {
    "Homepro": {
      "costUnit": 70.0935,
      "costCase": 1401.8692
    }
  },
  "4008239589255": {
    "Homepro": {
      "costUnit": 70.0935,
      "costCase": 1401.8692
    }
  },
  "4008239589262": {
    "Homepro": {
      "costUnit": 70.0935,
      "costCase": 1401.8692
    }
  },
  "4008239589781": {
    "Homepro": {
      "costUnit": 462.6168,
      "costCase": 2313.0841
    }
  },
  "4008239589798": {
    "Homepro": {
      "costUnit": 462.6168,
      "costCase": 2313.0841
    }
  },
  "4008239594112": {
    "Homepro": {
      "costUnit": 303.7383,
      "costCase": 1822.4299
    }
  },
  "4008239594105": {
    "Homepro": {
      "costUnit": 303.7383,
      "costCase": 1822.4299
    }
  },
  "4008239140319": {
    "Homepro": {
      "costUnit": 640.1869,
      "costCase": 640.1869
    }
  },
  "4008239140296": {
    "Homepro": {
      "costUnit": 322.4299,
      "costCase": 322.4299
    }
  },
  "4008239160799": {
    "Homepro": {
      "costUnit": 640.1869,
      "costCase": 640.1869
    }
  },
  "4008239340474": {
    "Homepro": {
      "costUnit": 88.785,
      "costCase": 710.2804
    }
  },
  "4008239340481": {
    "Homepro": {
      "costUnit": 88.785,
      "costCase": 710.2804
    }
  },
  "4008239369192": {
    "Homepro": {
      "costUnit": 135.514,
      "costCase": 813.0841
    }
  },
  "4008239315908": {
    "Homepro": {
      "costUnit": 32.7103,
      "costCase": 1635.514
    }
  },
  "4008239315915": {
    "Homepro": {
      "costUnit": 32.7103,
      "costCase": 1635.514
    }
  },
  "4008239230294": {
    "Homepro": {
      "costUnit": 42.0561,
      "costCase": 2102.8037
    }
  },
  "4008239340511": {
    "Homepro": {
      "costUnit": 42.0561,
      "costCase": 2102.8037
    }
  },
  "4008239340528": {
    "Homepro": {
      "costUnit": 42.0561,
      "costCase": 2102.8037
    }
  },
  "4008239595188": {
    "Homepro": {
      "costUnit": 79.4393,
      "costCase": 1985.9813
    }
  },
  "4008239589224": {
    "Homepro": {
      "costUnit": 79.4393,
      "costCase": 2224.2991
    }
  },
  "4008239589217": {
    "Homepro": {
      "costUnit": 79.4393,
      "costCase": 2224.2991
    }
  },
  "4008239288011": {
    "Homepro": {
      "costUnit": 163.5514,
      "costCase": 1144.8598
    }
  },
  "4008239223050": {
    "Homepro": {
      "costUnit": 116.8224,
      "costCase": 1401.8692
    }
  },
  "4008239223067": {
    "Homepro": {
      "costUnit": 135.514,
      "costCase": 1626.1682
    }
  },
  "4008239233912": {
    "Homepro": {
      "costUnit": 257.0093,
      "costCase": 3084.1121
    }
  },
  "4000530683755": {
    "Homepro": {
      "costUnit": 1210.2804,
      "costCase": 1210.2804,
      "gp": 0.3
    }
  },
  "4000530735065": {
    "Homepro": {
      "costUnit": 1733.6449,
      "costCase": 1733.6449,
      "gp": 0.3
    }
  },
  "4000530683212": {
    "Homepro": {
      "costUnit": 2558.4112,
      "costCase": 2558.4112,
      "gp": 0.25
    }
  },
  "4000530683229": {
    "Homepro": {
      "costUnit": 2978.972,
      "costCase": 2978.972,
      "gp": 0.25
    }
  },
  "4000530735584": {
    "Homepro": {
      "costUnit": 4205.6075,
      "costCase": 4205.6075,
      "gp": 0.25
    },
    "Central Department": {
      "costUnit": 3644.8598,
      "gp": 0.35
    }
  },
  "4800888152916": {
    "Big C": {
      "costUnit": 66.5888,
      "costCase": 3196.2617,
      "gp": 0.25
    }
  },
  "8999999028701": {
    "Big C": {
      "costUnit": 66.5888,
      "costCase": 3196.2617,
      "gp": 0.25
    }
  },
  "8999999534769": {
    "Big C": {
      "costUnit": 87.6168,
      "costCase": 4205.6075,
      "gp": 0.25
    }
  },
  "8999999710866": {
    "Big C": {
      "costUnit": 101.6355,
      "costCase": 4878.5047,
      "gp": 0.25
    }
  },
  "8999999707781": {
    "Big C": {
      "costUnit": 101.6355,
      "costCase": 4878.5047,
      "gp": 0.25
    }
  },
  "8999999032883": {
    "Big C": {
      "costUnit": 94.6262,
      "costCase": 3406.5421,
      "gp": 0.25
    }
  },
  "8999999032890": {
    "Big C": {
      "costUnit": 94.6262,
      "costCase": 3406.5421,
      "gp": 0.25
    }
  },
  "8999999035563": {
    "Big C": {
      "costUnit": 94.6262,
      "costCase": 3406.5421,
      "gp": 0.25
    }
  },
  "8999999008505": {
    "Big C": {
      "costUnit": 94.6262,
      "costCase": 3406.5421,
      "gp": 0.25
    }
  },
  "079400835000": {
    "Big C": {
      "costUnit": 129.6729,
      "costCase": 778.0374,
      "gp": 0.25
    }
  },
  "079400602862": {
    "Big C": {
      "costUnit": 129.6729,
      "costCase": 778.0374,
      "gp": 0.25
    }
  },
  "079400118868": {
    "Big C": {
      "costUnit": 129.6729,
      "costCase": 778.0374,
      "gp": 0.25
    }
  },
  "079400040374": {
    "Big C": {
      "costUnit": 129.6729,
      "costCase": 778.0374,
      "gp": 0.25
    }
  },
  "079400459534": {
    "Big C": {
      "costUnit": 192.757,
      "costCase": 1156.5421,
      "gp": 0.25
    }
  },
  "4000530547057": {
    "Central Department": {
      "costUnit": 1488.3178,
      "gp": 0.35
    }
  },
  "4000530562234": {
    "Central Department": {
      "costUnit": 1397.1963,
      "gp": 0.35
    }
  },
  "4000530685827": {
    "Central Department": {
      "costUnit": 3541.5888,
      "gp": 0.35
    }
  },
  "4000530534910": {
    "Central Department": {
      "costUnit": 807.9439,
      "gp": 0.35
    }
  },
  "4000530549556": {
    "Central Department": {
      "costUnit": 656.0748,
      "gp": 0.35
    }
  },
  "4000530681096": {
    "Central Department": {
      "costUnit": 8109.8131,
      "gp": 0.35
    }
  },
  "4000530732972": {
    "Central Department": {
      "costUnit": 8006.5421,
      "gp": 0.35
    }
  },
  "4000530597809": {
    "Central Department": {
      "costUnit": 2915.8879,
      "gp": 0.35
    }
  },
  "4000530597793": {
    "Central Department": {
      "costUnit": 2417.757,
      "gp": 0.35
    }
  },
  "4000530705709": {
    "Central Department": {
      "costUnit": 10327.1028,
      "gp": 0.35
    }
  },
  "4000530705808": {
    "Central Department": {
      "costUnit": 8249.5327,
      "gp": 0.35
    }
  },
  "4000530708007": {
    "Central Department": {
      "costUnit": 9385.514,
      "gp": 0.35
    }
  },
  "4000530628756": {
    "Central Department": {
      "costUnit": 8626.1682,
      "gp": 0.35
    }
  },
  "4000530649577": {
    "Central Department": {
      "costUnit": 2842.9907,
      "gp": 0.35
    }
  },
  "4000530581860": {
    "Central Department": {
      "costUnit": 2733.6449,
      "gp": 0.35
    }
  },
  "4000530715289": {
    "Central Department": {
      "costUnit": 3274.2991,
      "gp": 0.35
    }
  },
  "4000530715296": {
    "Central Department": {
      "costUnit": 3754.2056,
      "gp": 0.35
    }
  },
  "4000530710857": {
    "Central Department": {
      "costUnit": 2842.9907,
      "gp": 0.35
    }
  },
  "4000530497901": {
    "Central Department": {
      "costUnit": 2782.243,
      "gp": 0.35
    }
  },
  "4000530708564": {
    "Central Department": {
      "costUnit": 1810.2804,
      "gp": 0.35
    }
  },
  "4000530644831": {
    "Central Department": {
      "costUnit": 1427.5701,
      "gp": 0.35
    }
  },
  "4000530692108": {
    "Central Department": {
      "costUnit": 3025.2336,
      "gp": 0.35
    }
  },
  "4000530537126": {
    "Central Department": {
      "costUnit": 564.9533,
      "gp": 0.35
    }
  },
  "4000530559876": {
    "Central Department": {
      "costUnit": 577.1028,
      "gp": 0.35
    }
  },
  "4000530534903": {
    "Central Department": {
      "costUnit": 637.8505,
      "gp": 0.35
    }
  },
  "4000530730572": {
    "Central Department": {
      "costUnit": 20520.5607,
      "gp": 0.35
    }
  },
  "4000530578228": {
    "Central Department": {
      "costUnit": 759.3458,
      "gp": 0.35
    }
  },
  "4000530552068": {
    "Central Department": {
      "costUnit": 607.4766,
      "gp": 0.35
    }
  },
  "4000530534958": {
    "Central Department": {
      "costUnit": 777.5701,
      "gp": 0.35
    }
  },
  "4000530534927": {
    "Central Department": {
      "costUnit": 637.8505,
      "gp": 0.35
    }
  },
  "4000530548900": {
    "Central Department": {
      "costUnit": 880.8411,
      "gp": 0.35
    }
  },
  "4000530572172": {
    "Central Department": {
      "costUnit": 7642.0561,
      "gp": 0.35
    }
  },
  "4000530643995": {
    "Central Department": {
      "costUnit": 13455.6075,
      "gp": 0.35
    }
  },
  "4000530683694": {
    "Central Department": {
      "costUnit": 6226.6355,
      "gp": 0.35
    }
  },
  "4000530692696": {
    "Central Department": {
      "costUnit": 1427.5701,
      "gp": 0.35
    }
  },
  "4000530573773": {
    "Central Department": {
      "costUnit": 850.4673,
      "gp": 0.35
    }
  },
  "4000530534880": {
    "Central Department": {
      "costUnit": 753.271,
      "gp": 0.35
    }
  },
  "4000530535023": {
    "Central Department": {
      "costUnit": 686.4486,
      "gp": 0.35
    }
  },
  "4000530535016": {
    "Central Department": {
      "costUnit": 595.3271,
      "gp": 0.35
    }
  },
  "4000530588920": {
    "Central Department": {
      "costUnit": 929.4393,
      "gp": 0.35
    }
  },
  "4000530535184": {
    "Central Department": {
      "costUnit": 382.7103,
      "gp": 0.35
    }
  },
  "4000530548917": {
    "Central Department": {
      "costUnit": 728.972,
      "gp": 0.35
    }
  },
  "4000530676863": {
    "Central Department": {
      "costUnit": 6378.5047,
      "gp": 0.35
    }
  },
  "4000530547651": {
    "Central Department": {
      "costUnit": 4100.4673,
      "gp": 0.35
    }
  },
  "4000530676771": {
    "Central Department": {
      "costUnit": 5862.1495,
      "gp": 0.35
    }
  },
  "4000530676764": {
    "Central Department": {
      "costUnit": 6062.6168,
      "gp": 0.35
    }
  },
  "4000530676740": {
    "Central Department": {
      "costUnit": 4878.0374,
      "gp": 0.35
    }
  },
  "4000530676726": {
    "Central Department": {
      "costUnit": 8978.5047,
      "gp": 0.35
    }
  },
  "4000530676733": {
    "Central Department": {
      "costUnit": 9464.486,
      "gp": 0.35
    }
  },
  "4000530676702": {
    "Central Department": {
      "costUnit": 7307.9439,
      "gp": 0.35
    }
  },
  "4000530676689": {
    "Central Department": {
      "costUnit": 7016.3551,
      "gp": 0.35
    }
  },
  "4000530676641": {
    "Central Department": {
      "costUnit": 5121.028,
      "gp": 0.35
    }
  },
  "4000530671936": {
    "Central Department": {
      "costUnit": 4738.3178,
      "gp": 0.35
    }
  },
  "4000530677792": {
    "Central Department": {
      "costUnit": 5485.514,
      "gp": 0.35
    }
  },
  "4000530677853": {
    "Central Department": {
      "costUnit": 3978.972,
      "gp": 0.35
    }
  },
  "4000530677914": {
    "Central Department": {
      "costUnit": 5376.1682,
      "gp": 0.35
    }
  },
  "4000530677884": {
    "Central Department": {
      "costUnit": 5212.1495,
      "gp": 0.35
    }
  },
  "4000530678058": {
    "Central Department": {
      "costUnit": 4859.8131,
      "gp": 0.35
    }
  },
  "4000530678089": {
    "Central Department": {
      "costUnit": 4221.9626,
      "gp": 0.35
    }
  },
  "4000530738400": {
    "Central Department": {
      "costUnit": 29146.729,
      "gp": 0.35
    }
  },
  "4000530738912": {
    "Central Department": {
      "costUnit": 34838.785,
      "gp": 0.35
    }
  },
  "4000530738479": {
    "Central Department": {
      "costUnit": 22039.2523,
      "gp": 0.35
    }
  },
  "4000530664327": {
    "Central Department": {
      "costUnit": 941.5888,
      "gp": 0.35
    }
  },
  "4000530732934": {
    "Central Department": {
      "costUnit": 13078.972,
      "gp": 0.35
    }
  },
  "4000530571212": {
    "Central Department": {
      "costUnit": 9932.243,
      "gp": 0.35
    }
  },
  "4000530475022": {
    "Central Department": {
      "costUnit": 1992.5234,
      "gp": 0.35
    }
  },
  "4000530471949": {
    "Central Department": {
      "costUnit": 3280.3738,
      "gp": 0.35
    }
  },
  "4000530645197": {
    "Central Department": {
      "costUnit": 1415.4206,
      "gp": 0.35
    }
  },
  "4000530678034": {
    "Central Department": {
      "costUnit": 4009.3458,
      "gp": 0.35
    }
  },
  "4000530504173": {
    "Central Department": {
      "costUnit": 2672.8972,
      "gp": 0.35
    }
  },
  "4000530321985": {
    "Central Department": {
      "costUnit": 5831.7757,
      "gp": 0.35
    }
  },
  "4000530584137": {
    "Central Department": {
      "costUnit": 990.1869,
      "gp": 0.35
    }
  },
  "4000530735775": {
    "Central Department": {
      "costUnit": 17768.6916,
      "gp": 0.35
    }
  },
  "4000530702500": {
    "Central Department": {
      "costUnit": 672.224,
      "gp": 0.28
    }
  }
}
export default RETAILER_DATA
